
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for ScriptedActionsGroupDelete.
.Description
Create an in-memory object for ScriptedActionsGroupDelete.

.Outputs
NmePowershell.Models.ScriptedActionsGroupDelete

#>
function New-NmeScriptedActionsGroupDeleteModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.ScriptedActionsGroupDelete')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [bool]
        $Force
    )

    process {
        $Object = [NmePowershell.Models.ScriptedActionsGroupDelete]::New()

        if ($PSBoundParameters.ContainsKey('Force')) {
            $Object.Force = $Force
        }
        return $Object
    }
}

