
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for ScriptedActionsGroupItemCreate.
.Description
Create an in-memory object for ScriptedActionsGroupItemCreate.

.Outputs
NmePowershell.Models.ScriptedActionsGroupItemCreate

#>
function New-NmeScriptedActionsGroupItemCreateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.ScriptedActionsGroupItemCreate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(HelpMessage="Dictionary of <ScriptedActionParamValue>.")]
        [NmePowershell.Models.IScriptedActionsGroupItemCreateDefaultParams]
        $DefaultParams,
        [Parameter(Mandatory)]
        [int]
        $ScriptedActionId
    )

    process {
        $Object = [NmePowershell.Models.ScriptedActionsGroupItemCreate]::New()

        if ($PSBoundParameters.ContainsKey('DefaultParams')) {
            $Object.DefaultParams = $DefaultParams
        }
        if ($PSBoundParameters.ContainsKey('ScriptedActionId')) {
            $Object.ScriptedActionId = $ScriptedActionId
        }
        return $Object
    }
}

