
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for ScriptedActionsGroupUpdate.
.Description
Create an in-memory object for ScriptedActionsGroupUpdate.

.Outputs
NmePowershell.Models.ScriptedActionsGroupUpdate

#>
function New-NmeScriptedActionsGroupUpdateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.ScriptedActionsGroupUpdate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [string]
        $Description,
        [Parameter()]
        [string]
        $Name,
        [Parameter()]
        [NmePowershell.Models.IScriptedActionsGroupItemUpdate[]]
        $ScriptedActions,
        [Parameter()]
        [string[]]
        $Tags
    )

    process {
        $Object = [NmePowershell.Models.ScriptedActionsGroupUpdate]::New()

        if ($PSBoundParameters.ContainsKey('Description')) {
            $Object.Description = $Description
        }
        if ($PSBoundParameters.ContainsKey('Name')) {
            $Object.Name = $Name
        }
        if ($PSBoundParameters.ContainsKey('ScriptedActions')) {
            $Object.ScriptedActions = $ScriptedActions
        }
        if ($PSBoundParameters.ContainsKey('Tags')) {
            $Object.Tags = $Tags
        }
        return $Object
    }
}

