
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.9, generator: @autorest/powershell@4.0.758)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for DynamicPoolConfiguration.
.Description
Create an in-memory object for DynamicPoolConfiguration.

.Outputs
NmePowershell.Models.DynamicPoolConfiguration

#>
function New-NmeDynamicPoolConfigurationModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.DynamicPoolConfiguration')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("Running", "AvailableForConnection")]
        [string]
        $ActiveHostType,
        [Parameter()]
        [int]
        $ActiveSessionsScaleCriteriaScaleInHostChangeCount,
        [Parameter()]
        [float]
        $ActiveSessionsScaleCriteriaScaleInValue,
        [Parameter()]
        [int]
        $ActiveSessionsScaleCriteriaScaleOutHostChangeCount,
        [Parameter()]
        [float]
        $ActiveSessionsScaleCriteriaScaleOutValue,
        [Parameter()]
        [string[]]
        $AdditionalNetworks,
        [Parameter()]
        [NmePowershell.Models.IAutoHealConfigurationItem[]]
        $AutoHealConfigs,
        [Parameter(Mandatory)]
        [bool]
        $AutoHealEnable,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("CPUUsage", "RAMUsage", "AvgActiveSessions", "AvailableUserSessionSingle", "AvailableUserSessions", "UserDriven", "PersonalAutoGrow", "PersonalAutoShrink")]
        [string]
        $AutoScaleCriteria,
        [Parameter()]
        [int]
        $AutoScaleInterval,
        [Parameter()]
        [NmePowershell.Models.IDynamicPoolTriggerInfo[]]
        $AutoScaleTriggers,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("Always", "DuringWorkHours")]
        [string]
        $AvailableUserSessionScaleCriterionAvailableSessionRestriction,
        [Parameter()]
        [string]
        $AvailableUserSessionScaleCriterionEndWorkHours,
        [Parameter()]
        [int]
        $AvailableUserSessionScaleCriterionMaxAvailableUserSessions,
        [Parameter()]
        [int]
        $AvailableUserSessionScaleCriterionMinAvailableUserSessions,
        [Parameter()]
        [int]
        $AvailableUserSessionScaleCriterionOutsideWorkHoursSessions,
        [Parameter(Mandatory)]
        [int]
        $BurstCapacity,
        [Parameter()]
        [NmePowershell.Models.IAutoHealAction[]]
        $ConfigActions,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("0", "1", "2", "3", "4", "5", "6")]
        [int[]]
        $ConfigDays,
        [Parameter()]
        [int]
        $ConfigHostsToBeReady,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("Count", "Percent")]
        [string]
        $ConfigHostsToBeReadyMeasureType,
        [Parameter()]
        [string]
        $ConfigNetworkId,
        [Parameter()]
        [bool]
        $ConfigPreStageDiskType,
        [Parameter()]
        [bool]
        $ConfigPreStageUnassigned,
        [Parameter()]
        [bool]
        $ConfigPreStageUnassignedHosts,
        [Parameter()]
        [string]
        $ConfigPrefix,
        [Parameter()]
        [string]
        $ConfigResourceGroupId,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("WithoutSessions", "WithoutActive", "WithActive")]
        [string]
        $ConfigSessionCriteria,
        [Parameter()]
        [int]
        $ConfigStaleHeartbeatMinutes,
        [Parameter()]
        [string]
        $ConfigSubnet,
        [Parameter()]
        [int]
        $ConfigWaitMinutes,
        [Parameter()]
        [int]
        $ConfigWaitMinutesBeforeFirstAction,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("Available", "Unavailable", "Shutdown", "Disconnected", "Upgrading", "UpgradeFailed", "NoHeartbeat", "NotJoinedToDomain", "DomainTrustRelationshipLost", "SxSStackListenerNotReady", "FSLogixNotHealthy", "NeedsAssistance")]
        [string[]]
        $ConfigWvdStatuses,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("BreadthFirst", "DepthFirst", "Persistent", "MultiplePersistent")]
        [string]
        $ExtensionLoadBalancing,
        [Parameter()]
        [int]
        $ExtensionMaxSessionsPerHost,
        [Parameter()]
        [bool]
        $ExtensionStartVMOnConnect,
        [Parameter(Mandatory)]
        [int]
        $HostPoolCapacity,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("Count", "Percent")]
        [string]
        $HostPoolSizingMeasureType,
        [Parameter()]
        [int]
        $HostUsageScaleCriteriaScaleInHostChangeCount,
        [Parameter()]
        [float]
        $HostUsageScaleCriteriaScaleInValue,
        [Parameter()]
        [int]
        $HostUsageScaleCriteriaScaleOutHostChangeCount,
        [Parameter()]
        [float]
        $HostUsageScaleCriteriaScaleOutValue,
        [Parameter(Mandatory)]
        [bool]
        $IsEnabled,
        [Parameter(Mandatory)]
        [bool]
        $IsSingleUserDesktop,
        [Parameter(Mandatory)]
        [int]
        $MinActiveHostsCount,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("DepthFirst", "BreadthFirst")]
        [string]
        $NetworkDistributionStrategy,
        [Parameter()]
        [NmePowershell.Models.IPreStageHostsConfigurationItem[]]
        $PreStageHostConfigs,
        [Parameter(Mandatory)]
        [bool]
        $PreStageHostEnable,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("Hybrid", "Automated")]
        [string]
        $PreStageHostIntelligentPrestageMode,
        [Parameter()]
        [bool]
        $PreStageHostIsMultipleConfigsMode,
        [Parameter(Mandatory)]
        [bool]
        $ReImageUsedHosts,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("Disabled", "Always", "OnlyWhenScaleInIsAllowed")]
        [string]
        $ReImageUsedHostsMode,
        [Parameter()]
        [string]
        $RemoveMessagingMessage,
        [Parameter()]
        [int]
        $RemoveMessagingMinutesBeforeRemove,
        [Parameter()]
        [bool]
        $RollingDrainModeIsEnabled,
        [Parameter()]
        [NmePowershell.Models.IRollingDrainModeWindow[]]
        $RollingDrainModeWindows,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("High", "Medium", "Low")]
        [string]
        $ScaleInAggressiveness,
        [Parameter()]
        [int]
        $ScaleInAverageTimeRangeInMinutes,
        [Parameter(Mandatory)]
        [bool]
        $ScaleInRestrictionEnable,
        [Parameter(Mandatory)]
        [bool]
        $ScaleInRestrictionPutToDrainMode,
        [Parameter()]
        [int]
        $ScaleOutAverageTimeRangeInMinutes,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("Default", "WorkingHours", "UserDriven")]
        [string]
        $ScalingMode,
        [Parameter()]
        [bool]
        $SecondaryRegionEnabled,
        [Parameter()]
        [int]
        $StartWorkDuration,
        [Parameter()]
        [int]
        $StartWorkHour,
        [Parameter()]
        [int]
        $StartWorkMinutes,
        [Parameter()]
        [string]
        $StoppedDiskType,
        [Parameter()]
        [int]
        $TimeRangeEndHour,
        [Parameter()]
        [int]
        $TimeRangeEndMinutes,
        [Parameter()]
        [int]
        $TimeRangeStartHour,
        [Parameter()]
        [int]
        $TimeRangeStartMinutes,
        [Parameter()]
        [string]
        $TimezoneId,
        [Parameter()]
        [bool]
        $UserDrivenBypassDrainMode,
        [Parameter()]
        [int]
        $UserDrivenMinAvailableSessions,
        [Parameter()]
        [NmePowershell.Models.IUserDrivenPreStageHostsConfigurationItem[]]
        $UserDrivenPreStageHostConfigs,
        [Parameter()]
        [bool]
        $UserDrivenPreStageHostEnable,
        [Parameter()]
        [bool]
        $UserDrivenPreStageHostPreStageIfUnassigned,
        [Parameter()]
        [int]
        $UserDrivenStopDelayMinutes,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("Standard", "Reuse", "Unique")]
        [string]
        $VMNamingMode,
        [Parameter()]
        [string]
        $VMTemplateDiskPerformanceTier,
        [Parameter()]
        [int]
        $VMTemplateDiskSize,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("CacheDisk", "ResourceDisk", "NvmeDisk")]
        [string]
        $VMTemplateEphemeralOsdiskPlacement,
        [Parameter()]
        [bool]
        $VMTemplateHasEphemeralOsdisk,
        [Parameter()]
        [string]
        $VMTemplateImage,
        [Parameter()]
        [string]
        $VMTemplateNetworkId,
        [Parameter()]
        [string]
        $VMTemplatePrefix,
        [Parameter()]
        [string]
        $VMTemplateResourceGroupId,
        [Parameter()]
        [string]
        $VMTemplateSize,
        [Parameter()]
        [string]
        $VMTemplateStorageType,
        [Parameter()]
        [string]
        $VMTemplateSubnet,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("OneTime", "Continuously", "Never")]
        [string]
        $WorkingHoursScaleInBehavior,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("OneTime", "Continuously", "Never")]
        [string]
        $WorkingHoursScaleOutBehavior
    )

    process {
        $Object = [NmePowershell.Models.DynamicPoolConfiguration]::New()

        if ($PSBoundParameters.ContainsKey('ActiveHostType')) {
            $Object.ActiveHostType = $ActiveHostType
        }
        if ($PSBoundParameters.ContainsKey('ActiveSessionsScaleCriteriaScaleInHostChangeCount')) {
            $Object.ActiveSessionsScaleCriteriaScaleInHostChangeCount = $ActiveSessionsScaleCriteriaScaleInHostChangeCount
        }
        if ($PSBoundParameters.ContainsKey('ActiveSessionsScaleCriteriaScaleInValue')) {
            $Object.ActiveSessionsScaleCriteriaScaleInValue = $ActiveSessionsScaleCriteriaScaleInValue
        }
        if ($PSBoundParameters.ContainsKey('ActiveSessionsScaleCriteriaScaleOutHostChangeCount')) {
            $Object.ActiveSessionsScaleCriteriaScaleOutHostChangeCount = $ActiveSessionsScaleCriteriaScaleOutHostChangeCount
        }
        if ($PSBoundParameters.ContainsKey('ActiveSessionsScaleCriteriaScaleOutValue')) {
            $Object.ActiveSessionsScaleCriteriaScaleOutValue = $ActiveSessionsScaleCriteriaScaleOutValue
        }
        if ($PSBoundParameters.ContainsKey('AdditionalNetworks')) {
            $Object.AdditionalNetworks = $AdditionalNetworks
        }
        if ($PSBoundParameters.ContainsKey('AutoHealConfigs')) {
            $Object.AutoHealConfigs = $AutoHealConfigs
        }
        if ($PSBoundParameters.ContainsKey('AutoHealEnable')) {
            $Object.AutoHealEnable = $AutoHealEnable
        }
        if ($PSBoundParameters.ContainsKey('AutoScaleCriteria')) {
            $Object.AutoScaleCriteria = $AutoScaleCriteria
        }
        if ($PSBoundParameters.ContainsKey('AutoScaleInterval')) {
            $Object.AutoScaleInterval = $AutoScaleInterval
        }
        if ($PSBoundParameters.ContainsKey('AutoScaleTriggers')) {
            $Object.AutoScaleTriggers = $AutoScaleTriggers
        }
        if ($PSBoundParameters.ContainsKey('AvailableUserSessionScaleCriterionAvailableSessionRestriction')) {
            $Object.AvailableUserSessionScaleCriterionAvailableSessionRestriction = $AvailableUserSessionScaleCriterionAvailableSessionRestriction
        }
        if ($PSBoundParameters.ContainsKey('AvailableUserSessionScaleCriterionEndWorkHours')) {
            $Object.AvailableUserSessionScaleCriterionEndWorkHours = $AvailableUserSessionScaleCriterionEndWorkHours
        }
        if ($PSBoundParameters.ContainsKey('AvailableUserSessionScaleCriterionMaxAvailableUserSessions')) {
            $Object.AvailableUserSessionScaleCriterionMaxAvailableUserSessions = $AvailableUserSessionScaleCriterionMaxAvailableUserSessions
        }
        if ($PSBoundParameters.ContainsKey('AvailableUserSessionScaleCriterionMinAvailableUserSessions')) {
            $Object.AvailableUserSessionScaleCriterionMinAvailableUserSessions = $AvailableUserSessionScaleCriterionMinAvailableUserSessions
        }
        if ($PSBoundParameters.ContainsKey('AvailableUserSessionScaleCriterionOutsideWorkHoursSessions')) {
            $Object.AvailableUserSessionScaleCriterionOutsideWorkHoursSessions = $AvailableUserSessionScaleCriterionOutsideWorkHoursSessions
        }
        if ($PSBoundParameters.ContainsKey('BurstCapacity')) {
            $Object.BurstCapacity = $BurstCapacity
        }
        if ($PSBoundParameters.ContainsKey('ConfigActions')) {
            $Object.ConfigActions = $ConfigActions
        }
        if ($PSBoundParameters.ContainsKey('ConfigDays')) {
            $Object.ConfigDays = $ConfigDays
        }
        if ($PSBoundParameters.ContainsKey('ConfigHostsToBeReady')) {
            $Object.ConfigHostsToBeReady = $ConfigHostsToBeReady
        }
        if ($PSBoundParameters.ContainsKey('ConfigHostsToBeReadyMeasureType')) {
            $Object.ConfigHostsToBeReadyMeasureType = $ConfigHostsToBeReadyMeasureType
        }
        if ($PSBoundParameters.ContainsKey('ConfigNetworkId')) {
            $Object.ConfigNetworkId = $ConfigNetworkId
        }
        if ($PSBoundParameters.ContainsKey('ConfigPreStageDiskType')) {
            $Object.ConfigPreStageDiskType = $ConfigPreStageDiskType
        }
        if ($PSBoundParameters.ContainsKey('ConfigPreStageUnassigned')) {
            $Object.ConfigPreStageUnassigned = $ConfigPreStageUnassigned
        }
        if ($PSBoundParameters.ContainsKey('ConfigPreStageUnassignedHosts')) {
            $Object.ConfigPreStageUnassignedHosts = $ConfigPreStageUnassignedHosts
        }
        if ($PSBoundParameters.ContainsKey('ConfigPrefix')) {
            $Object.ConfigPrefix = $ConfigPrefix
        }
        if ($PSBoundParameters.ContainsKey('ConfigResourceGroupId')) {
            $Object.ConfigResourceGroupId = $ConfigResourceGroupId
        }
        if ($PSBoundParameters.ContainsKey('ConfigSessionCriteria')) {
            $Object.ConfigSessionCriteria = $ConfigSessionCriteria
        }
        if ($PSBoundParameters.ContainsKey('ConfigStaleHeartbeatMinutes')) {
            $Object.ConfigStaleHeartbeatMinutes = $ConfigStaleHeartbeatMinutes
        }
        if ($PSBoundParameters.ContainsKey('ConfigSubnet')) {
            $Object.ConfigSubnet = $ConfigSubnet
        }
        if ($PSBoundParameters.ContainsKey('ConfigWaitMinutes')) {
            $Object.ConfigWaitMinutes = $ConfigWaitMinutes
        }
        if ($PSBoundParameters.ContainsKey('ConfigWaitMinutesBeforeFirstAction')) {
            $Object.ConfigWaitMinutesBeforeFirstAction = $ConfigWaitMinutesBeforeFirstAction
        }
        if ($PSBoundParameters.ContainsKey('ConfigWvdStatuses')) {
            $Object.ConfigWvdStatuses = $ConfigWvdStatuses
        }
        if ($PSBoundParameters.ContainsKey('ExtensionLoadBalancing')) {
            $Object.ExtensionLoadBalancing = $ExtensionLoadBalancing
        }
        if ($PSBoundParameters.ContainsKey('ExtensionMaxSessionsPerHost')) {
            $Object.ExtensionMaxSessionsPerHost = $ExtensionMaxSessionsPerHost
        }
        if ($PSBoundParameters.ContainsKey('ExtensionStartVMOnConnect')) {
            $Object.ExtensionStartVMOnConnect = $ExtensionStartVMOnConnect
        }
        if ($PSBoundParameters.ContainsKey('HostPoolCapacity')) {
            $Object.HostPoolCapacity = $HostPoolCapacity
        }
        if ($PSBoundParameters.ContainsKey('HostPoolSizingMeasureType')) {
            $Object.HostPoolSizingMeasureType = $HostPoolSizingMeasureType
        }
        if ($PSBoundParameters.ContainsKey('HostUsageScaleCriteriaScaleInHostChangeCount')) {
            $Object.HostUsageScaleCriteriaScaleInHostChangeCount = $HostUsageScaleCriteriaScaleInHostChangeCount
        }
        if ($PSBoundParameters.ContainsKey('HostUsageScaleCriteriaScaleInValue')) {
            $Object.HostUsageScaleCriteriaScaleInValue = $HostUsageScaleCriteriaScaleInValue
        }
        if ($PSBoundParameters.ContainsKey('HostUsageScaleCriteriaScaleOutHostChangeCount')) {
            $Object.HostUsageScaleCriteriaScaleOutHostChangeCount = $HostUsageScaleCriteriaScaleOutHostChangeCount
        }
        if ($PSBoundParameters.ContainsKey('HostUsageScaleCriteriaScaleOutValue')) {
            $Object.HostUsageScaleCriteriaScaleOutValue = $HostUsageScaleCriteriaScaleOutValue
        }
        if ($PSBoundParameters.ContainsKey('IsEnabled')) {
            $Object.IsEnabled = $IsEnabled
        }
        if ($PSBoundParameters.ContainsKey('IsSingleUserDesktop')) {
            $Object.IsSingleUserDesktop = $IsSingleUserDesktop
        }
        if ($PSBoundParameters.ContainsKey('MinActiveHostsCount')) {
            $Object.MinActiveHostsCount = $MinActiveHostsCount
        }
        if ($PSBoundParameters.ContainsKey('NetworkDistributionStrategy')) {
            $Object.NetworkDistributionStrategy = $NetworkDistributionStrategy
        }
        if ($PSBoundParameters.ContainsKey('PreStageHostConfigs')) {
            $Object.PreStageHostConfigs = $PreStageHostConfigs
        }
        if ($PSBoundParameters.ContainsKey('PreStageHostEnable')) {
            $Object.PreStageHostEnable = $PreStageHostEnable
        }
        if ($PSBoundParameters.ContainsKey('PreStageHostIntelligentPrestageMode')) {
            $Object.PreStageHostIntelligentPrestageMode = $PreStageHostIntelligentPrestageMode
        }
        if ($PSBoundParameters.ContainsKey('PreStageHostIsMultipleConfigsMode')) {
            $Object.PreStageHostIsMultipleConfigsMode = $PreStageHostIsMultipleConfigsMode
        }
        if ($PSBoundParameters.ContainsKey('ReImageUsedHosts')) {
            $Object.ReImageUsedHosts = $ReImageUsedHosts
        }
        if ($PSBoundParameters.ContainsKey('ReImageUsedHostsMode')) {
            $Object.ReImageUsedHostsMode = $ReImageUsedHostsMode
        }
        if ($PSBoundParameters.ContainsKey('RemoveMessagingMessage')) {
            $Object.RemoveMessagingMessage = $RemoveMessagingMessage
        }
        if ($PSBoundParameters.ContainsKey('RemoveMessagingMinutesBeforeRemove')) {
            $Object.RemoveMessagingMinutesBeforeRemove = $RemoveMessagingMinutesBeforeRemove
        }
        if ($PSBoundParameters.ContainsKey('RollingDrainModeIsEnabled')) {
            $Object.RollingDrainModeIsEnabled = $RollingDrainModeIsEnabled
        }
        if ($PSBoundParameters.ContainsKey('RollingDrainModeWindows')) {
            $Object.RollingDrainModeWindows = $RollingDrainModeWindows
        }
        if ($PSBoundParameters.ContainsKey('ScaleInAggressiveness')) {
            $Object.ScaleInAggressiveness = $ScaleInAggressiveness
        }
        if ($PSBoundParameters.ContainsKey('ScaleInAverageTimeRangeInMinutes')) {
            $Object.ScaleInAverageTimeRangeInMinutes = $ScaleInAverageTimeRangeInMinutes
        }
        if ($PSBoundParameters.ContainsKey('ScaleInRestrictionEnable')) {
            $Object.ScaleInRestrictionEnable = $ScaleInRestrictionEnable
        }
        if ($PSBoundParameters.ContainsKey('ScaleInRestrictionPutToDrainMode')) {
            $Object.ScaleInRestrictionPutToDrainMode = $ScaleInRestrictionPutToDrainMode
        }
        if ($PSBoundParameters.ContainsKey('ScaleOutAverageTimeRangeInMinutes')) {
            $Object.ScaleOutAverageTimeRangeInMinutes = $ScaleOutAverageTimeRangeInMinutes
        }
        if ($PSBoundParameters.ContainsKey('ScalingMode')) {
            $Object.ScalingMode = $ScalingMode
        }
        if ($PSBoundParameters.ContainsKey('SecondaryRegionEnabled')) {
            $Object.SecondaryRegionEnabled = $SecondaryRegionEnabled
        }
        if ($PSBoundParameters.ContainsKey('StartWorkDuration')) {
            $Object.StartWorkDuration = $StartWorkDuration
        }
        if ($PSBoundParameters.ContainsKey('StartWorkHour')) {
            $Object.StartWorkHour = $StartWorkHour
        }
        if ($PSBoundParameters.ContainsKey('StartWorkMinutes')) {
            $Object.StartWorkMinutes = $StartWorkMinutes
        }
        if ($PSBoundParameters.ContainsKey('StoppedDiskType')) {
            $Object.StoppedDiskType = $StoppedDiskType
        }
        if ($PSBoundParameters.ContainsKey('TimeRangeEndHour')) {
            $Object.TimeRangeEndHour = $TimeRangeEndHour
        }
        if ($PSBoundParameters.ContainsKey('TimeRangeEndMinutes')) {
            $Object.TimeRangeEndMinutes = $TimeRangeEndMinutes
        }
        if ($PSBoundParameters.ContainsKey('TimeRangeStartHour')) {
            $Object.TimeRangeStartHour = $TimeRangeStartHour
        }
        if ($PSBoundParameters.ContainsKey('TimeRangeStartMinutes')) {
            $Object.TimeRangeStartMinutes = $TimeRangeStartMinutes
        }
        if ($PSBoundParameters.ContainsKey('TimezoneId')) {
            $Object.TimezoneId = $TimezoneId
        }
        if ($PSBoundParameters.ContainsKey('UserDrivenBypassDrainMode')) {
            $Object.UserDrivenBypassDrainMode = $UserDrivenBypassDrainMode
        }
        if ($PSBoundParameters.ContainsKey('UserDrivenMinAvailableSessions')) {
            $Object.UserDrivenMinAvailableSessions = $UserDrivenMinAvailableSessions
        }
        if ($PSBoundParameters.ContainsKey('UserDrivenPreStageHostConfigs')) {
            $Object.UserDrivenPreStageHostConfigs = $UserDrivenPreStageHostConfigs
        }
        if ($PSBoundParameters.ContainsKey('UserDrivenPreStageHostEnable')) {
            $Object.UserDrivenPreStageHostEnable = $UserDrivenPreStageHostEnable
        }
        if ($PSBoundParameters.ContainsKey('UserDrivenPreStageHostPreStageIfUnassigned')) {
            $Object.UserDrivenPreStageHostPreStageIfUnassigned = $UserDrivenPreStageHostPreStageIfUnassigned
        }
        if ($PSBoundParameters.ContainsKey('UserDrivenStopDelayMinutes')) {
            $Object.UserDrivenStopDelayMinutes = $UserDrivenStopDelayMinutes
        }
        if ($PSBoundParameters.ContainsKey('VMNamingMode')) {
            $Object.VMNamingMode = $VMNamingMode
        }
        if ($PSBoundParameters.ContainsKey('VMTemplateDiskPerformanceTier')) {
            $Object.VMTemplateDiskPerformanceTier = $VMTemplateDiskPerformanceTier
        }
        if ($PSBoundParameters.ContainsKey('VMTemplateDiskSize')) {
            $Object.VMTemplateDiskSize = $VMTemplateDiskSize
        }
        if ($PSBoundParameters.ContainsKey('VMTemplateEphemeralOsdiskPlacement')) {
            $Object.VMTemplateEphemeralOsdiskPlacement = $VMTemplateEphemeralOsdiskPlacement
        }
        if ($PSBoundParameters.ContainsKey('VMTemplateHasEphemeralOsdisk')) {
            $Object.VMTemplateHasEphemeralOsdisk = $VMTemplateHasEphemeralOsdisk
        }
        if ($PSBoundParameters.ContainsKey('VMTemplateImage')) {
            $Object.VMTemplateImage = $VMTemplateImage
        }
        if ($PSBoundParameters.ContainsKey('VMTemplateNetworkId')) {
            $Object.VMTemplateNetworkId = $VMTemplateNetworkId
        }
        if ($PSBoundParameters.ContainsKey('VMTemplatePrefix')) {
            $Object.VMTemplatePrefix = $VMTemplatePrefix
        }
        if ($PSBoundParameters.ContainsKey('VMTemplateResourceGroupId')) {
            $Object.VMTemplateResourceGroupId = $VMTemplateResourceGroupId
        }
        if ($PSBoundParameters.ContainsKey('VMTemplateSize')) {
            $Object.VMTemplateSize = $VMTemplateSize
        }
        if ($PSBoundParameters.ContainsKey('VMTemplateStorageType')) {
            $Object.VMTemplateStorageType = $VMTemplateStorageType
        }
        if ($PSBoundParameters.ContainsKey('VMTemplateSubnet')) {
            $Object.VMTemplateSubnet = $VMTemplateSubnet
        }
        if ($PSBoundParameters.ContainsKey('WorkingHoursScaleInBehavior')) {
            $Object.WorkingHoursScaleInBehavior = $WorkingHoursScaleInBehavior
        }
        if ($PSBoundParameters.ContainsKey('WorkingHoursScaleOutBehavior')) {
            $Object.WorkingHoursScaleOutBehavior = $WorkingHoursScaleOutBehavior
        }
        return $Object
    }
}


# SIG # Begin signature block
# MIIvWQYJKoZIhvcNAQcCoIIvSjCCL0YCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCDR5gGPQxCD37BJ
# hnty4Jf1mzx9LDu/mgG2COwVDo1Mk6CCFAUwggWQMIIDeKADAgECAhAFmxtXno4h
# MuI5B72nd3VcMA0GCSqGSIb3DQEBDAUAMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQK
# EwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNV
# BAMTGERpZ2lDZXJ0IFRydXN0ZWQgUm9vdCBHNDAeFw0xMzA4MDExMjAwMDBaFw0z
# ODAxMTUxMjAwMDBaMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJ
# bmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNVBAMTGERpZ2lDZXJ0
# IFRydXN0ZWQgUm9vdCBHNDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
# AL/mkHNo3rvkXUo8MCIwaTPswqclLskhPfKK2FnC4SmnPVirdprNrnsbhA3EMB/z
# G6Q4FutWxpdtHauyefLKEdLkX9YFPFIPUh/GnhWlfr6fqVcWWVVyr2iTcMKyunWZ
# anMylNEQRBAu34LzB4TmdDttceItDBvuINXJIB1jKS3O7F5OyJP4IWGbNOsFxl7s
# Wxq868nPzaw0QF+xembud8hIqGZXV59UWI4MK7dPpzDZVu7Ke13jrclPXuU15zHL
# 2pNe3I6PgNq2kZhAkHnDeMe2scS1ahg4AxCN2NQ3pC4FfYj1gj4QkXCrVYJBMtfb
# BHMqbpEBfCFM1LyuGwN1XXhm2ToxRJozQL8I11pJpMLmqaBn3aQnvKFPObURWBf3
# JFxGj2T3wWmIdph2PVldQnaHiZdpekjw4KISG2aadMreSx7nDmOu5tTvkpI6nj3c
# AORFJYm2mkQZK37AlLTSYW3rM9nF30sEAMx9HJXDj/chsrIRt7t/8tWMcCxBYKqx
# YxhElRp2Yn72gLD76GSmM9GJB+G9t+ZDpBi4pncB4Q+UDCEdslQpJYls5Q5SUUd0
# viastkF13nqsX40/ybzTQRESW+UQUOsxxcpyFiIJ33xMdT9j7CFfxCBRa2+xq4aL
# T8LWRV+dIPyhHsXAj6KxfgommfXkaS+YHS312amyHeUbAgMBAAGjQjBAMA8GA1Ud
# EwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGGMB0GA1UdDgQWBBTs1+OC0nFdZEzf
# Lmc/57qYrhwPTzANBgkqhkiG9w0BAQwFAAOCAgEAu2HZfalsvhfEkRvDoaIAjeNk
# aA9Wz3eucPn9mkqZucl4XAwMX+TmFClWCzZJXURj4K2clhhmGyMNPXnpbWvWVPjS
# PMFDQK4dUPVS/JA7u5iZaWvHwaeoaKQn3J35J64whbn2Z006Po9ZOSJTROvIXQPK
# 7VB6fWIhCoDIc2bRoAVgX+iltKevqPdtNZx8WorWojiZ83iL9E3SIAveBO6Mm0eB
# cg3AFDLvMFkuruBx8lbkapdvklBtlo1oepqyNhR6BvIkuQkRUNcIsbiJeoQjYUIp
# 5aPNoiBB19GcZNnqJqGLFNdMGbJQQXE9P01wI4YMStyB0swylIQNCAmXHE/A7msg
# dDDS4Dk0EIUhFQEI6FUy3nFJ2SgXUE3mvk3RdazQyvtBuEOlqtPDBURPLDab4vri
# RbgjU2wGb2dVf0a1TD9uKFp5JtKkqGKX0h7i7UqLvBv9R0oN32dmfrJbQdA75PQ7
# 9ARj6e/CVABRoIoqyc54zNXqhwQYs86vSYiv85KZtrPmYQ/ShQDnUBrkG5WdGaG5
# nLGbsQAe79APT0JsyQq87kP6OnGlyE0mpTX9iV28hWIdMtKgK1TtmlfB2/oQzxm3
# i0objwG2J5VT6LaJbVu8aNQj6ItRolb58KaAoNYes7wPD1N1KarqE3fk3oyBIa0H
# EEcRrYc9B9F1vM/zZn4wggawMIIEmKADAgECAhAIrUCyYNKcTJ9ezam9k67ZMA0G
# CSqGSIb3DQEBDAUAMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJ
# bmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNVBAMTGERpZ2lDZXJ0
# IFRydXN0ZWQgUm9vdCBHNDAeFw0yMTA0MjkwMDAwMDBaFw0zNjA0MjgyMzU5NTla
# MGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwgSW5jLjFBMD8GA1UE
# AxM4RGlnaUNlcnQgVHJ1c3RlZCBHNCBDb2RlIFNpZ25pbmcgUlNBNDA5NiBTSEEz
# ODQgMjAyMSBDQTEwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDVtC9C
# 0CiteLdd1TlZG7GIQvUzjOs9gZdwxbvEhSYwn6SOaNhc9es0JAfhS0/TeEP0F9ce
# 2vnS1WcaUk8OoVf8iJnBkcyBAz5NcCRks43iCH00fUyAVxJrQ5qZ8sU7H/Lvy0da
# E6ZMswEgJfMQ04uy+wjwiuCdCcBlp/qYgEk1hz1RGeiQIXhFLqGfLOEYwhrMxe6T
# SXBCMo/7xuoc82VokaJNTIIRSFJo3hC9FFdd6BgTZcV/sk+FLEikVoQ11vkunKoA
# FdE3/hoGlMJ8yOobMubKwvSnowMOdKWvObarYBLj6Na59zHh3K3kGKDYwSNHR7Oh
# D26jq22YBoMbt2pnLdK9RBqSEIGPsDsJ18ebMlrC/2pgVItJwZPt4bRc4G/rJvmM
# 1bL5OBDm6s6R9b7T+2+TYTRcvJNFKIM2KmYoX7BzzosmJQayg9Rc9hUZTO1i4F4z
# 8ujo7AqnsAMrkbI2eb73rQgedaZlzLvjSFDzd5Ea/ttQokbIYViY9XwCFjyDKK05
# huzUtw1T0PhH5nUwjewwk3YUpltLXXRhTT8SkXbev1jLchApQfDVxW0mdmgRQRNY
# mtwmKwH0iU1Z23jPgUo+QEdfyYFQc4UQIyFZYIpkVMHMIRroOBl8ZhzNeDhFMJlP
# /2NPTLuqDQhTQXxYPUez+rbsjDIJAsxsPAxWEQIDAQABo4IBWTCCAVUwEgYDVR0T
# AQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUaDfg67Y7+F8Rhvv+YXsIiGX0TkIwHwYD
# VR0jBBgwFoAU7NfjgtJxXWRM3y5nP+e6mK4cD08wDgYDVR0PAQH/BAQDAgGGMBMG
# A1UdJQQMMAoGCCsGAQUFBwMDMHcGCCsGAQUFBwEBBGswaTAkBggrBgEFBQcwAYYY
# aHR0cDovL29jc3AuZGlnaWNlcnQuY29tMEEGCCsGAQUFBzAChjVodHRwOi8vY2Fj
# ZXJ0cy5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVzdGVkUm9vdEc0LmNydDBDBgNV
# HR8EPDA6MDigNqA0hjJodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNlcnRU
# cnVzdGVkUm9vdEc0LmNybDAcBgNVHSAEFTATMAcGBWeBDAEDMAgGBmeBDAEEATAN
# BgkqhkiG9w0BAQwFAAOCAgEAOiNEPY0Idu6PvDqZ01bgAhql+Eg08yy25nRm95Ry
# sQDKr2wwJxMSnpBEn0v9nqN8JtU3vDpdSG2V1T9J9Ce7FoFFUP2cvbaF4HZ+N3HL
# IvdaqpDP9ZNq4+sg0dVQeYiaiorBtr2hSBh+3NiAGhEZGM1hmYFW9snjdufE5Btf
# Q/g+lP92OT2e1JnPSt0o618moZVYSNUa/tcnP/2Q0XaG3RywYFzzDaju4ImhvTnh
# OE7abrs2nfvlIVNaw8rpavGiPttDuDPITzgUkpn13c5UbdldAhQfQDN8A+KVssIh
# dXNSy0bYxDQcoqVLjc1vdjcshT8azibpGL6QB7BDf5WIIIJw8MzK7/0pNVwfiThV
# 9zeKiwmhywvpMRr/LhlcOXHhvpynCgbWJme3kuZOX956rEnPLqR0kq3bPKSchh/j
# wVYbKyP/j7XqiHtwa+aguv06P0WmxOgWkVKLQcBIhEuWTatEQOON8BUozu3xGFYH
# Ki8QxAwIZDwzj64ojDzLj4gLDb879M4ee47vtevLt/B3E+bnKD+sEq6lLyJsQfmC
# XBVmzGwOysWGw/YmMwwHS6DTBwJqakAwSEs0qFEgu60bhQjiWQ1tygVQK+pKHJ6l
# /aCnHwZ05/LWUpD9r4VIIflXO7ScA+2GRfS0YW6/aOImYIbqyK+p/pQd52MbOoZW
# eE4wgge5MIIFoaADAgECAhALDOX/BzyGPKP6JnAWOAwdMA0GCSqGSIb3DQEBCwUA
# MGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwgSW5jLjFBMD8GA1UE
# AxM4RGlnaUNlcnQgVHJ1c3RlZCBHNCBDb2RlIFNpZ25pbmcgUlNBNDA5NiBTSEEz
# ODQgMjAyMSBDQTEwHhcNMjYwODE5MDAwMDAwWhcNMjcwODE4MjM1OTU5WjCBwTET
# MBEGCysGAQQBgjc8AgEDEwJVUzEZMBcGCysGAQQBgjc8AgECEwhEZWxhd2FyZTEd
# MBsGA1UEDwwUUHJpdmF0ZSBPcmdhbml6YXRpb24xEDAOBgNVBAUTBzY2NzU5MTMx
# CzAJBgNVBAYTAlVTMREwDwYDVQQIEwhJbGxpbm9pczEQMA4GA1UEBxMHQ2hpY2Fn
# bzEVMBMGA1UEChMMTmVyZGlvLCBJbmMuMRUwEwYDVQQDEwxOZXJkaW8sIEluYy4w
# ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC0GAXkl6ecx6CDQ9QXP+mP
# oa2GWMIs5Tcw0/BtIZY3EjaJXq9Nmm4RHM+XSnRgae88aXnrIixdz9FIzp1uZ30E
# 4ztt8mfowmP7qhX2dS0BMTn3JN53x6vPsTbgrE419zkAMm2d7QjxSxVk+3dzCCDa
# FBiCe68aVGpRkqbRNMpwC3EoE8/2stzyi/njYbcTCzazXmjBqV7kz0DZfF0xLigt
# 4CWGnY1LxS9dJBESnKKH4dQLyKBpkDA2IM29bEiDhLnSg/wWIX+0lufTX0v3euIh
# tTBGB85lBZXjKt/dqKexGMBmou5WZT9sttYRXLsG9pflvBEhLmOAqA+inS98ii9C
# vd6Ly9D5adcR3InBBBHIx8kQFLOglRiEMCyUYoJ9K0AaHl8xxD0to+J4chG9hLvI
# 1bik+Q7z5Ut2NbdJwV22YLe41wJIQEtZynN2vKhM5GX5nokebXescojq0jeprZU6
# oSFpdcNmIOOBb9iGEpFhD9WvaoT0G6dn9GdCPypxZY3JBL+J8LxGwoxX4eaKx/e/
# 8O5a5FBVz/0yYL17hUmuLBZHtZcsw31cAnovm4DQ9jMBce1VlwrUFKevNzCAW3CR
# RVQx2DEcLTyWP8d6Dczsmy4hQEpUfgiLxyrWduxhNRJ9j/FUVq6AV9+J5gBlB/3H
# QaNVjIyplLqs/6yJRIHh6QIDAQABo4ICAjCCAf4wHwYDVR0jBBgwFoAUaDfg67Y7
# +F8Rhvv+YXsIiGX0TkIwHQYDVR0OBBYEFNQPOC7V6GMYGn9bFaoCiWTci1QwMD0G
# A1UdIAQ2MDQwMgYFZ4EMAQMwKTAnBggrBgEFBQcCARYbaHR0cDovL3d3dy5kaWdp
# Y2VydC5jb20vQ1BTMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcD
# AzCBtQYDVR0fBIGtMIGqMFOgUaBPhk1odHRwOi8vY3JsMy5kaWdpY2VydC5jb20v
# RGlnaUNlcnRUcnVzdGVkRzRDb2RlU2lnbmluZ1JTQTQwOTZTSEEzODQyMDIxQ0Ex
# LmNybDBToFGgT4ZNaHR0cDovL2NybDQuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0VHJ1
# c3RlZEc0Q29kZVNpZ25pbmdSU0E0MDk2U0hBMzg0MjAyMUNBMS5jcmwwgZQGCCsG
# AQUFBwEBBIGHMIGEMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5j
# b20wXAYIKwYBBQUHMAKGUGh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdp
# Q2VydFRydXN0ZWRHNENvZGVTaWduaW5nUlNBNDA5NlNIQTM4NDIwMjFDQTEuY3J0
# MAkGA1UdEwQCMAAwDQYJKoZIhvcNAQELBQADggIBAMrdNPV0udYeYciAelPfj2x0
# VCnkSr1byoRXxsHV2U9jM0xdp0afCHRoaxLIZFvi8M8UzNkvfMelct1gVbIp7ygd
# yYjV0DlOdYVALzmfOuZPzwC02cvtqZkZ3j1sWN/9enqRQiPHv2iZkAdWGWYIvPRW
# q9xT7Qh/+4MsOMdnjleGcb95drHt2s4NagL4/haq1t+Wo+45D6v0r8kUedHLJF4P
# 6MtEbu1vdS1zWysT0SyrK3X3GjaRB6cTLL5S1GtPE92sEc3XU0V4gi8DFKV0Tcko
# ZXaDApg9KTaNii79jr/DLiejN41PODsYNM+zmROUiSHktvAbLV2w0vn0QDB8raCy
# vVBfCkQHqAeuWTQypFRf0NttZ9l9obEGdag2XjibCDZ1qRyjP8dr+XUwRGNZDwIP
# edZN7Bg+F9CA2VHHJHqYzsEOP9GbUAsq6J7i0E5V3ftb4n1327nFKu0HE2BJshz9
# lrRSz2F5fq69O7+imnHedVAUAN4gixuOLBJQMpSJ+YUs9mSlR8wnCCO5wp5kRnKT
# nNXyx6apTwr/ij5YPsH72iApunlJq/ashQd1e8P6ZTcerVXdUHr9Lr3n92sVky+/
# r3Le9IJlhnCQVjAdMsJ9WKa9IkOzC2sgHLe5Ea59kZO0BR/9PXFNyXsB5SAX9pGZ
# Ymvvxj8r7PzbSci8A4e6MYIaqjCCGqYCAQEwfTBpMQswCQYDVQQGEwJVUzEXMBUG
# A1UEChMORGlnaUNlcnQsIEluYy4xQTA/BgNVBAMTOERpZ2lDZXJ0IFRydXN0ZWQg
# RzQgQ29kZSBTaWduaW5nIFJTQTQwOTYgU0hBMzg0IDIwMjEgQ0ExAhALDOX/BzyG
# PKP6JnAWOAwdMA0GCWCGSAFlAwQCAQUAoIGEMBgGCisGAQQBgjcCAQwxCjAIoAKA
# AKECgAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIDO9u27a/Rnenb+nuxvmFXvQ
# L91Ggq6Dg6mUh4tEmRLwMA0GCSqGSIb3DQEBAQUABIICABpJ64UD/SwPuA+lntnR
# AaPQIirQLJfwer7FXj1qnf+buIQzk2yeHgsQRg/xK2k3W3fYkFU4Y0NSyNtvmpy3
# nCud56/lkjNhYKf95AN2gGYs8jLslTnPJBm9rfbSw7Ffq62SaDN00NP6lPrJ+0bb
# rCEmXqhcbhKJ7w5cRUH0zk0zyPBVfitqqehfjcBWPdTOWzmld/MLEIVD8yezpkwU
# 4UMyXpI9YJh3GcMh9GCAiejz2EFV4yebcYM6HCd1T7a6bsn5EWm9XBW3TGXnf1Tu
# k000bnvF0mTz6Gzwlu5GLbSEEDt60iSo2HI9fvGPKJeExM8qF2LGo3ZtJvvJ4V3/
# AdhCjPqArRXsFRK1G55R7WqWffh4xEaaoMIc3XIg9Hbz++fGKqp4PWRzJPPUkQ/m
# CTqmMz8YHFJ6LlmMSkpH9ny3e6ckxhYwrGGH5j1txI2B1tzvNTBDtCYkZ4kZ11o3
# qogLdaoZoeS7yYjetE/y8Qdnm2dAEdStmmFaVH2ry/Zx2EjAasd4wWSqTsjecYyW
# 8ZRrlMt1P8A6TkhkRHvusZ3YOBZzo14BqdyCCw/ZjTl99+gWL+OXtSUE+Xm5JGZf
# oZTYNYzDBcbluf96dP3lxC5bV0xKTMOyGOiGSfNJJhMUegIf9Er5roX5x+RQBqEI
# jBoFmvLXaS+FCA4/55Ad7r92oYIXdzCCF3MGCisGAQQBgjcDAwExghdjMIIXXwYJ
# KoZIhvcNAQcCoIIXUDCCF0wCAQMxDzANBglghkgBZQMEAgEFADB4BgsqhkiG9w0B
# CRABBKBpBGcwZQIBAQYJYIZIAYb9bAcBMDEwDQYJYIZIAWUDBAIBBQAEIBmwPOCa
# 2ARqp3JDhIPtnTMaQIwBpEaD3jHgDwtmX7X3AhEAqIDwUC6zNAHqohjlq9G6XxgP
# MjAyNjA5MTExMjIyNDVaoIITOjCCBu0wggTVoAMCAQICEAhP3DNPfkVO28MPj/mS
# GDUwDQYJKoZIhvcNAQELBQAwaTELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDkRpZ2lD
# ZXJ0LCBJbmMuMUEwPwYDVQQDEzhEaWdpQ2VydCBUcnVzdGVkIEc0IFRpbWVTdGFt
# cGluZyBSU0E0MDk2IFNIQTI1NiAyMDI1IENBMTAeFw0yNjA4MDUwMDAwMDBaFw0z
# NzExMDQyMzU5NTlaMGMxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwg
# SW5jLjE7MDkGA1UEAxMyRGlnaUNlcnQgU0hBMjU2IFJTQTQwOTYgVGltZXN0YW1w
# IFJlc3BvbmRlciAyMDI2IDEwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoIC
# AQC2e6byyf7NSvjUm0xls/04xjD4fAkOkbnGQi7+Wpx81iYxfzViaxSIctuH3KSl
# 5YEYpMuFgGsA31N2D9ATMbfZdw5uaAhuWevQKhDdZIB4NnqcfpfpWQXJiQnDdAEl
# ETC+bhSEvNLGbA8DtwUpFMQ4yyYQSPqomT92osQAv6hBi47ATZS6JfVWe6XxhF4j
# JZ3iSAuf2Cros1czRSmWRHqMv9AfGZvp8ygYElhudpQjtcPpwoOl6QrZJUyV3iIN
# vN4cO05prGV0fkjG426xDr2d3z9lcSIHkdvGPdGUrXdxfVbgOUVcp2/8ISEzwKPW
# ++Wa+E2ujI91EZtukGWDJ/xZ27k3oHKEXBRGfRTqjOU+jE3ba/5++JSE/7oNHnjs
# 5mekExYN96LV/mxUbCKJb8pBNY4r3uD7hEmk/M81XhVgwDA7aMzYC3LZBg9WY5BM
# mbSay5ecmtJuXaB/0nKWmQmVZeqTVDgsmzHP5MQuhAJkiWNuC9MmCg9TZHXbJ2/y
# LVSov9p16UDTLtT0+aa1vN71fHeu1qMLlLNB3WOB/ADCxr3S/1hxI92Z6jKgEED/
# btwIvbfuXkNNhg8MtDg43c4tMZae9FvqMOt/9PvmAxF9TNIsIFB8G6yb36ZJZGUL
# 8N/pL971DyLXcK6HM5PYnH5X+eVtczhCgHCVQCF6XDAlPQIDAQABo4IBlTCCAZEw
# DAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUFMljijAu1Er7bpTz5uNAfvXszeIwHwYD
# VR0jBBgwFoAU729TSunkBnx6yuKQVvYv1Ensy04wDgYDVR0PAQH/BAQDAgeAMBYG
# A1UdJQEB/wQMMAoGCCsGAQUFBwMIMIGVBggrBgEFBQcBAQSBiDCBhTAkBggrBgEF
# BQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29tMF0GCCsGAQUFBzAChlFodHRw
# Oi8vY2FjZXJ0cy5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVzdGVkRzRUaW1lU3Rh
# bXBpbmdSU0E0MDk2U0hBMjU2MjAyNUNBMS5jcnQwXwYDVR0fBFgwVjBUoFKgUIZO
# aHR0cDovL2NybDMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0VHJ1c3RlZEc0VGltZVN0
# YW1waW5nUlNBNDA5NlNIQTI1NjIwMjVDQTEuY3JsMCAGA1UdIAQZMBcwCAYGZ4EM
# AQQCMAsGCWCGSAGG/WwHATANBgkqhkiG9w0BAQsFAAOCAgEAjcU6YR6dUgrfmawJ
# gH59KECxa9Ji8sEi2g10CBDaMiqsaxWyW5cwlT/6ZF5sFznazqVsoC85U9dqLOYq
# Qwst+UQQoNlDHgKRLa3xoc+OReFreFhnTXSG0Vrd2E2CZqUfm+5a+He1MJ/h+tNL
# uA+0Zzhn/Fo+FDYAHWZHx4R79ZsfRFYe9UiXpXBDf6DkUo183Y38NYmR/XfDYf7Y
# Z+oR9t3flbDwK+hgGMs0gNNp1w9Z2CyOyI5or/sSwomAuNQ0hWC9xoU4stD8aWsD
# 7RkcmgVRs6vlIk3zPKQ+ylcheWkMlj+CoVRlFE55pv0ZWCaFt04lwP/rdGHE9qEV
# QZtyRE42ox7oNgC/r+Y4bSlZ3dw9K2x1xLtu6PkPKeLBFjzKigwfqm3Hm+k/+lnM
# E8F5kPZTgiy2HLEHklpryqs6QHnPXrRNeIzkAMyylnRN8P0wmirS0WkU+ywpEWFZ
# 4QNg+9xS43tTuW9x0eXh7NDc1P/sV+zWxHXKH8tFt1ncHdVzqrZaYPyYMLSn2TOX
# ajveJW1L3joiQSPsWRGxkbDDW15jERFE4LvjnGu2O9zD1nLJSMdlYZEikl4w2w+q
# 4IN/R+TIe0H4ngCI1moJCTbevGH4punIxM1Uoi0nmX3ZK+XbRT01uowE5ViXWHng
# 0RgsmrX/EdYUo80r3TfMlkD0/YMwgga0MIIEnKADAgECAhANx6xXBf8hmS5AQyIM
# OkmGMA0GCSqGSIb3DQEBCwUAMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdp
# Q2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNVBAMTGERp
# Z2lDZXJ0IFRydXN0ZWQgUm9vdCBHNDAeFw0yNTA1MDcwMDAwMDBaFw0zODAxMTQy
# MzU5NTlaMGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwgSW5jLjFB
# MD8GA1UEAxM4RGlnaUNlcnQgVHJ1c3RlZCBHNCBUaW1lU3RhbXBpbmcgUlNBNDA5
# NiBTSEEyNTYgMjAyNSBDQTEwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoIC
# AQC0eDHTCphBcr48RsAcrHXbo0ZodLRRF51NrY0NlLWZloMsVO1DahGPNRcybEKq
# +RuwOnPhof6pvF4uGjwjqNjfEvUi6wuim5bap+0lgloM2zX4kftn5B1IpYzTqpyF
# Q/4Bt0mAxAHeHYNnQxqXmRinvuNgxVBdJkf77S2uPoCj7GH8BLuxBG5AvftBdsOE
# CS1UkxBvMgEdgkFiDNYiOTx4OtiFcMSkqTtF2hfQz3zQSku2Ws3IfDReb6e3mmdg
# lTcaarps0wjUjsZvkgFkriK9tUKJm/s80FiocSk1VYLZlDwFt+cVFBURJg6zMUjZ
# a/zbCclF83bRVFLeGkuAhHiGPMvSGmhgaTzVyhYn4p0+8y9oHRaQT/aofEnS5xLr
# fxnGpTXiUOeSLsJygoLPp66bkDX1ZlAeSpQl92QOMeRxykvq6gbylsXQskBBBnGy
# 3tW/AMOMCZIVNSaz7BX8VtYGqLt9MmeOreGPRdtBx3yGOP+rx3rKWDEJlIqLXvJW
# nY0v5ydPpOjL6s36czwzsucuoKs7Yk/ehb//Wx+5kMqIMRvUBDx6z1ev+7psNOdg
# JMoiwOrUG2ZdSoQbU2rMkpLiQ6bGRinZbI4OLu9BMIFm1UUl9VnePs6BaaeEWvjJ
# SjNm2qA+sdFUeEY0qVjPKOWug/G6X5uAiynM7Bu2ayBjUwIDAQABo4IBXTCCAVkw
# EgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQU729TSunkBnx6yuKQVvYv1Ens
# y04wHwYDVR0jBBgwFoAU7NfjgtJxXWRM3y5nP+e6mK4cD08wDgYDVR0PAQH/BAQD
# AgGGMBMGA1UdJQQMMAoGCCsGAQUFBwMIMHcGCCsGAQUFBwEBBGswaTAkBggrBgEF
# BQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29tMEEGCCsGAQUFBzAChjVodHRw
# Oi8vY2FjZXJ0cy5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVzdGVkUm9vdEc0LmNy
# dDBDBgNVHR8EPDA6MDigNqA0hjJodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGln
# aUNlcnRUcnVzdGVkUm9vdEc0LmNybDAgBgNVHSAEGTAXMAgGBmeBDAEEAjALBglg
# hkgBhv1sBwEwDQYJKoZIhvcNAQELBQADggIBABfO+xaAHP4HPRF2cTC9vgvItTSm
# f83Qh8WIGjB/T8ObXAZz8OjuhUxjaaFdleMM0lBryPTQM2qEJPe36zwbSI/mS83a
# fsl3YTj+IQhQE7jU/kXjjytJgnn0hvrV6hqWGd3rLAUt6vJy9lMDPjTLxLgXf9r5
# nWMQwr8Myb9rEVKChHyfpzee5kH0F8HABBgr0UdqirZ7bowe9Vj2AIMD8liyrukZ
# 2iA/wdG2th9y1IsA0QF8dTXqvcnTmpfeQh35k5zOCPmSNq1UH410ANVko43+Cdmu
# 4y81hjajV/gxdEkMx1NKU4uHQcKfZxAvBAKqMVuqte69M9J6A47OvgRaPs+2ykgc
# GV00TYr2Lr3ty9qIijanrUR3anzEwlvzZiiyfTPjLbnFRsjsYg39OlV8cipDoq7+
# qNNjqFzeGxcytL5TTLL4ZaoBdqbhOhZ3ZRDUphPvSRmMThi0vw9vODRzW6AxnJll
# 38F0cuJG7uEBYTptMSbhdhGQDpOXgpIUsWTjd6xpR6oaQf/DJbg3s6KCLPAlZ66R
# zIg9sC+NJpud/v4+7RWsWCiKi9EOLLHfMR2ZyJ/+xhCx9yHbxtl5TPau1j/1MIDp
# MPx0LckTetiSuEtQvLsNz3Qbp7wGWqbIiOWCnb5WqxL3/BAPvIXKUjPSxyZsq8Wh
# baM2tszWkPZPubdcMIIFjTCCBHWgAwIBAgIQDpsYjvnQLefv21DiCEAYWjANBgkq
# hkiG9w0BAQwFADBlMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5j
# MRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMSQwIgYDVQQDExtEaWdpQ2VydCBB
# c3N1cmVkIElEIFJvb3QgQ0EwHhcNMjIwODAxMDAwMDAwWhcNMzExMTA5MjM1OTU5
# WjBiMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQL
# ExB3d3cuZGlnaWNlcnQuY29tMSEwHwYDVQQDExhEaWdpQ2VydCBUcnVzdGVkIFJv
# b3QgRzQwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC/5pBzaN675F1K
# PDAiMGkz7MKnJS7JIT3yithZwuEppz1Yq3aaza57G4QNxDAf8xukOBbrVsaXbR2r
# snnyyhHS5F/WBTxSD1Ifxp4VpX6+n6lXFllVcq9ok3DCsrp1mWpzMpTREEQQLt+C
# 8weE5nQ7bXHiLQwb7iDVySAdYyktzuxeTsiT+CFhmzTrBcZe7FsavOvJz82sNEBf
# sXpm7nfISKhmV1efVFiODCu3T6cw2Vbuyntd463JT17lNecxy9qTXtyOj4DatpGY
# QJB5w3jHtrHEtWoYOAMQjdjUN6QuBX2I9YI+EJFwq1WCQTLX2wRzKm6RAXwhTNS8
# rhsDdV14Ztk6MUSaM0C/CNdaSaTC5qmgZ92kJ7yhTzm1EVgX9yRcRo9k98FpiHaY
# dj1ZXUJ2h4mXaXpI8OCiEhtmmnTK3kse5w5jrubU75KSOp493ADkRSWJtppEGSt+
# wJS00mFt6zPZxd9LBADMfRyVw4/3IbKyEbe7f/LVjHAsQWCqsWMYRJUadmJ+9oCw
# ++hkpjPRiQfhvbfmQ6QYuKZ3AeEPlAwhHbJUKSWJbOUOUlFHdL4mrLZBdd56rF+N
# P8m800ERElvlEFDrMcXKchYiCd98THU/Y+whX8QgUWtvsauGi0/C1kVfnSD8oR7F
# wI+isX4KJpn15GkvmB0t9dmpsh3lGwIDAQABo4IBOjCCATYwDwYDVR0TAQH/BAUw
# AwEB/zAdBgNVHQ4EFgQU7NfjgtJxXWRM3y5nP+e6mK4cD08wHwYDVR0jBBgwFoAU
# Reuir/SSy4IxLVGLp6chnfNtyA8wDgYDVR0PAQH/BAQDAgGGMHkGCCsGAQUFBwEB
# BG0wazAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29tMEMGCCsG
# AQUFBzAChjdodHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20vRGlnaUNlcnRBc3N1
# cmVkSURSb290Q0EuY3J0MEUGA1UdHwQ+MDwwOqA4oDaGNGh0dHA6Ly9jcmwzLmRp
# Z2ljZXJ0LmNvbS9EaWdpQ2VydEFzc3VyZWRJRFJvb3RDQS5jcmwwEQYDVR0gBAow
# CDAGBgRVHSAAMA0GCSqGSIb3DQEBDAUAA4IBAQBwoL9DXFXnOF+go3QbPbYW1/e/
# Vwe9mqyhhyzshV6pGrsi+IcaaVQi7aSId229GhT0E0p6Ly23OO/0/4C5+KH38nLe
# JLxSA8hO0Cre+i1Wz/n096wwepqLsl7Uz9FDRJtDIeuWcqFItJnLnU+nBgMTdydE
# 1Od/6Fmo8L8vC6bp8jQ87PcDx4eo0kxAGTVGamlUsLihVo7spNU96LHc/RzY9Hda
# XFSMb++hUD38dglohJ9vytsgjTVgHAIDyyCwrFigDkBjxZgiwbJZ9VVrzyerbHbO
# byMt9H5xaiNrIv8SuFQtJ37YOtnwtoeW/VvRXKwYw02fc7cBqZ9Xql4o4rmUMYID
# fDCCA3gCAQEwfTBpMQswCQYDVQQGEwJVUzEXMBUGA1UEChMORGlnaUNlcnQsIElu
# Yy4xQTA/BgNVBAMTOERpZ2lDZXJ0IFRydXN0ZWQgRzQgVGltZVN0YW1waW5nIFJT
# QTQwOTYgU0hBMjU2IDIwMjUgQ0ExAhAIT9wzT35FTtvDD4/5khg1MA0GCWCGSAFl
# AwQCAQUAoIHRMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAcBgkqhkiG9w0B
# CQUxDxcNMjYwOTExMTIyMjQ1WjArBgsqhkiG9w0BCRACDDEcMBowGDAWBBRR2ava
# A0lz2E9CZqykgkjms2nEOTAvBgkqhkiG9w0BCQQxIgQghYowwdea8P1JuJo3M8EY
# z8PwakgnxFN84tIp9xVOoyIwNwYLKoZIhvcNAQkQAi8xKDAmMCQwIgQgLaCdp/QT
# H5/nLbbF5unJZWdVrwQ/HqdCzA0hIOFB6/wwDQYJKoZIhvcNAQEBBQAEggIAYtIs
# kSyS+Eutg5ud4T4p/jlmotd22FriNoORfmRO/JtkplNtlOORrI1AOSm+pRG2xo/t
# nBwB3Cxc1fYxWcuGa2LMV+M1u0xHOnUftp+WnbZgECbZcVjTeNCcfAtlVjPBodeY
# t8dVbOuUKSj2NH49VmB6z5tDmDq7wN1X9acz7E+eXRZ0TawDR9uD4xQ9KckiIyi2
# w7cy30TVpukuZaDwKViHHw7iw/aG6adndveVn8D6J+ZsjJa9Th9ODrco5nZ6IsUb
# Mvxk0uBqBmX7DRAmLRMdZW6bVp5+suo/VxEYLhM+QBLjweiLd1pBcaJ5BB9Ijkl/
# AkmSY+JTQgpQiMIZClw1JjJqTO0j3RZOKcdWEWLTtB18yvxEA2vbw4ZBk2MIvHJP
# NzvQWswVHds7J1wPSW1ur96ULLDAgqjTE4l0GQ04ICw8Eoy4GbYXCxCDJycFl5/Z
# 8zCt724Adl/Cj2qksv6oIg4ORBM2aeCBsrDFxUytcqhbZLDfEH9PlIFvmRPos3AM
# Agk7aFqn6+oYqVQA57MRKyPV5MaPwV1dFZyoNtDuQQP/NwvAZqsUhoYmjALh2ZYE
# ip2B0SqgOOy5GxDDphKF+Zawfc9R70DwLvGSk09AR4fBp7OFCoHSJOfvG9SoQ8YI
# JXTH0bSF5QurdVThRRdfAR0rMT1ijaj3i/9345E=
# SIG # End signature block
