
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for HostPoolScriptedActionProfileConfigurationCreate.
.Description
Create an in-memory object for HostPoolScriptedActionProfileConfigurationCreate.

.Outputs
NmePowershell.Models.HostPoolScriptedActionProfileConfigurationCreate

#>
function New-NmeHostPoolScriptedActionProfileConfigurationCreateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.HostPoolScriptedActionProfileConfigurationCreate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [int]
        $ActiveDirectoryId,
        [Parameter(Mandatory)]
        [bool]
        $Enabled,
        [Parameter(Mandatory)]
        [NmePowershell.Models.IScriptedActionOption[]]
        $ScriptedActions
    )

    process {
        $Object = [NmePowershell.Models.HostPoolScriptedActionProfileConfigurationCreate]::New()

        if ($PSBoundParameters.ContainsKey('ActiveDirectoryId')) {
            $Object.ActiveDirectoryId = $ActiveDirectoryId
        }
        if ($PSBoundParameters.ContainsKey('Enabled')) {
            $Object.Enabled = $Enabled
        }
        if ($PSBoundParameters.ContainsKey('ScriptedActions')) {
            $Object.ScriptedActions = $ScriptedActions
        }
        return $Object
    }
}

