
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.9, generator: @autorest/powershell@4.0.758)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for HostPoolUserSelfServiceUpdate.
.Description
Create an in-memory object for HostPoolUserSelfServiceUpdate.

.Outputs
NmePowershell.Models.HostPoolUserSelfServiceUpdate

#>
function New-NmeHostPoolUserSelfServiceUpdateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.HostPoolUserSelfServiceUpdate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [bool]
        $AllowAppInstall,
        [Parameter()]
        [bool]
        $AllowChangePersonalDiskSize,
        [Parameter()]
        [bool]
        $AllowCreateVM,
        [Parameter()]
        [bool]
        $AllowReimageDesktops,
        [Parameter()]
        [bool]
        $AllowResetFsLogix,
        [Parameter()]
        [bool]
        $AllowResizeDesktops,
        [Parameter()]
        [bool]
        $AllowRestartDesktops,
        [Parameter()]
        [bool]
        $AllowRestoreDesktops,
        [Parameter()]
        [bool]
        $AllowRestrictAutoScale,
        [Parameter()]
        [bool]
        $AllowScriptedActions,
        [Parameter()]
        [bool]
        $AllowStartDesktops,
        [Parameter()]
        [bool]
        $AllowStopDesktops,
        [Parameter()]
        [bool]
        $AllowUpdateDesktopsTags,
        [Parameter()]
        [NmePowershell.Models.IAnySelfServiceAppCreate[]]
        $AllowedApps,
        [Parameter()]
        [NmePowershell.Models.IUserSelfServiceTag[]]
        $AllowedDesktopsTags,
        [Parameter()]
        [NmePowershell.Models.ISelfServiceDiskSize[]]
        $AllowedDiskOptions,
        [Parameter()]
        [string[]]
        $AllowedDiskSizes,
        [Parameter()]
        [string[]]
        $AllowedImages,
        [Parameter()]
        [NmePowershell.Models.IUserSelfServiceScriptedAction[]]
        $AllowedScriptedActions,
        [Parameter()]
        [string[]]
        $AllowedVMSizes,
        [Parameter()]
        [bool]
        $AutoRevertPersonalSize,
        [Parameter()]
        [int]
        $AutoRevertPersonalSizeMaxDelayHours,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("High", "Medium", "Low")]
        [string]
        $AutoRevertPersonalSizeSessionState,
        [Parameter()]
        [bool]
        $EnableUserSelfServicePortal,
        [Parameter()]
        [int]
        $MaxAutoScaleRestrictionPeriod,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("InstantRestoresOnly", "AllRecoveryPoints")]
        [string]
        $RecoveryMode
    )

    process {
        $Object = [NmePowershell.Models.HostPoolUserSelfServiceUpdate]::New()

        if ($PSBoundParameters.ContainsKey('AllowAppInstall')) {
            $Object.AllowAppInstall = $AllowAppInstall
        }
        if ($PSBoundParameters.ContainsKey('AllowChangePersonalDiskSize')) {
            $Object.AllowChangePersonalDiskSize = $AllowChangePersonalDiskSize
        }
        if ($PSBoundParameters.ContainsKey('AllowCreateVM')) {
            $Object.AllowCreateVM = $AllowCreateVM
        }
        if ($PSBoundParameters.ContainsKey('AllowReimageDesktops')) {
            $Object.AllowReimageDesktops = $AllowReimageDesktops
        }
        if ($PSBoundParameters.ContainsKey('AllowResetFsLogix')) {
            $Object.AllowResetFsLogix = $AllowResetFsLogix
        }
        if ($PSBoundParameters.ContainsKey('AllowResizeDesktops')) {
            $Object.AllowResizeDesktops = $AllowResizeDesktops
        }
        if ($PSBoundParameters.ContainsKey('AllowRestartDesktops')) {
            $Object.AllowRestartDesktops = $AllowRestartDesktops
        }
        if ($PSBoundParameters.ContainsKey('AllowRestoreDesktops')) {
            $Object.AllowRestoreDesktops = $AllowRestoreDesktops
        }
        if ($PSBoundParameters.ContainsKey('AllowRestrictAutoScale')) {
            $Object.AllowRestrictAutoScale = $AllowRestrictAutoScale
        }
        if ($PSBoundParameters.ContainsKey('AllowScriptedActions')) {
            $Object.AllowScriptedActions = $AllowScriptedActions
        }
        if ($PSBoundParameters.ContainsKey('AllowStartDesktops')) {
            $Object.AllowStartDesktops = $AllowStartDesktops
        }
        if ($PSBoundParameters.ContainsKey('AllowStopDesktops')) {
            $Object.AllowStopDesktops = $AllowStopDesktops
        }
        if ($PSBoundParameters.ContainsKey('AllowUpdateDesktopsTags')) {
            $Object.AllowUpdateDesktopsTags = $AllowUpdateDesktopsTags
        }
        if ($PSBoundParameters.ContainsKey('AllowedApps')) {
            $Object.AllowedApps = $AllowedApps
        }
        if ($PSBoundParameters.ContainsKey('AllowedDesktopsTags')) {
            $Object.AllowedDesktopsTags = $AllowedDesktopsTags
        }
        if ($PSBoundParameters.ContainsKey('AllowedDiskOptions')) {
            $Object.AllowedDiskOptions = $AllowedDiskOptions
        }
        if ($PSBoundParameters.ContainsKey('AllowedDiskSizes')) {
            $Object.AllowedDiskSizes = $AllowedDiskSizes
        }
        if ($PSBoundParameters.ContainsKey('AllowedImages')) {
            $Object.AllowedImages = $AllowedImages
        }
        if ($PSBoundParameters.ContainsKey('AllowedScriptedActions')) {
            $Object.AllowedScriptedActions = $AllowedScriptedActions
        }
        if ($PSBoundParameters.ContainsKey('AllowedVMSizes')) {
            $Object.AllowedVMSizes = $AllowedVMSizes
        }
        if ($PSBoundParameters.ContainsKey('AutoRevertPersonalSize')) {
            $Object.AutoRevertPersonalSize = $AutoRevertPersonalSize
        }
        if ($PSBoundParameters.ContainsKey('AutoRevertPersonalSizeMaxDelayHours')) {
            $Object.AutoRevertPersonalSizeMaxDelayHours = $AutoRevertPersonalSizeMaxDelayHours
        }
        if ($PSBoundParameters.ContainsKey('AutoRevertPersonalSizeSessionState')) {
            $Object.AutoRevertPersonalSizeSessionState = $AutoRevertPersonalSizeSessionState
        }
        if ($PSBoundParameters.ContainsKey('EnableUserSelfServicePortal')) {
            $Object.EnableUserSelfServicePortal = $EnableUserSelfServicePortal
        }
        if ($PSBoundParameters.ContainsKey('MaxAutoScaleRestrictionPeriod')) {
            $Object.MaxAutoScaleRestrictionPeriod = $MaxAutoScaleRestrictionPeriod
        }
        if ($PSBoundParameters.ContainsKey('RecoveryMode')) {
            $Object.RecoveryMode = $RecoveryMode
        }
        return $Object
    }
}


# SIG # Begin signature block
# MIIvWAYJKoZIhvcNAQcCoIIvSTCCL0UCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCAE85O9nmRRoZWw
# SWKi49Nyxk07qGumdJZKMixX9bWsT6CCFAUwggWQMIIDeKADAgECAhAFmxtXno4h
# MuI5B72nd3VcMA0GCSqGSIb3DQEBDAUAMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQK
# EwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNV
# BAMTGERpZ2lDZXJ0IFRydXN0ZWQgUm9vdCBHNDAeFw0xMzA4MDExMjAwMDBaFw0z
# ODAxMTUxMjAwMDBaMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJ
# bmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNVBAMTGERpZ2lDZXJ0
# IFRydXN0ZWQgUm9vdCBHNDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
# AL/mkHNo3rvkXUo8MCIwaTPswqclLskhPfKK2FnC4SmnPVirdprNrnsbhA3EMB/z
# G6Q4FutWxpdtHauyefLKEdLkX9YFPFIPUh/GnhWlfr6fqVcWWVVyr2iTcMKyunWZ
# anMylNEQRBAu34LzB4TmdDttceItDBvuINXJIB1jKS3O7F5OyJP4IWGbNOsFxl7s
# Wxq868nPzaw0QF+xembud8hIqGZXV59UWI4MK7dPpzDZVu7Ke13jrclPXuU15zHL
# 2pNe3I6PgNq2kZhAkHnDeMe2scS1ahg4AxCN2NQ3pC4FfYj1gj4QkXCrVYJBMtfb
# BHMqbpEBfCFM1LyuGwN1XXhm2ToxRJozQL8I11pJpMLmqaBn3aQnvKFPObURWBf3
# JFxGj2T3wWmIdph2PVldQnaHiZdpekjw4KISG2aadMreSx7nDmOu5tTvkpI6nj3c
# AORFJYm2mkQZK37AlLTSYW3rM9nF30sEAMx9HJXDj/chsrIRt7t/8tWMcCxBYKqx
# YxhElRp2Yn72gLD76GSmM9GJB+G9t+ZDpBi4pncB4Q+UDCEdslQpJYls5Q5SUUd0
# viastkF13nqsX40/ybzTQRESW+UQUOsxxcpyFiIJ33xMdT9j7CFfxCBRa2+xq4aL
# T8LWRV+dIPyhHsXAj6KxfgommfXkaS+YHS312amyHeUbAgMBAAGjQjBAMA8GA1Ud
# EwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGGMB0GA1UdDgQWBBTs1+OC0nFdZEzf
# Lmc/57qYrhwPTzANBgkqhkiG9w0BAQwFAAOCAgEAu2HZfalsvhfEkRvDoaIAjeNk
# aA9Wz3eucPn9mkqZucl4XAwMX+TmFClWCzZJXURj4K2clhhmGyMNPXnpbWvWVPjS
# PMFDQK4dUPVS/JA7u5iZaWvHwaeoaKQn3J35J64whbn2Z006Po9ZOSJTROvIXQPK
# 7VB6fWIhCoDIc2bRoAVgX+iltKevqPdtNZx8WorWojiZ83iL9E3SIAveBO6Mm0eB
# cg3AFDLvMFkuruBx8lbkapdvklBtlo1oepqyNhR6BvIkuQkRUNcIsbiJeoQjYUIp
# 5aPNoiBB19GcZNnqJqGLFNdMGbJQQXE9P01wI4YMStyB0swylIQNCAmXHE/A7msg
# dDDS4Dk0EIUhFQEI6FUy3nFJ2SgXUE3mvk3RdazQyvtBuEOlqtPDBURPLDab4vri
# RbgjU2wGb2dVf0a1TD9uKFp5JtKkqGKX0h7i7UqLvBv9R0oN32dmfrJbQdA75PQ7
# 9ARj6e/CVABRoIoqyc54zNXqhwQYs86vSYiv85KZtrPmYQ/ShQDnUBrkG5WdGaG5
# nLGbsQAe79APT0JsyQq87kP6OnGlyE0mpTX9iV28hWIdMtKgK1TtmlfB2/oQzxm3
# i0objwG2J5VT6LaJbVu8aNQj6ItRolb58KaAoNYes7wPD1N1KarqE3fk3oyBIa0H
# EEcRrYc9B9F1vM/zZn4wggawMIIEmKADAgECAhAIrUCyYNKcTJ9ezam9k67ZMA0G
# CSqGSIb3DQEBDAUAMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJ
# bmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNVBAMTGERpZ2lDZXJ0
# IFRydXN0ZWQgUm9vdCBHNDAeFw0yMTA0MjkwMDAwMDBaFw0zNjA0MjgyMzU5NTla
# MGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwgSW5jLjFBMD8GA1UE
# AxM4RGlnaUNlcnQgVHJ1c3RlZCBHNCBDb2RlIFNpZ25pbmcgUlNBNDA5NiBTSEEz
# ODQgMjAyMSBDQTEwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDVtC9C
# 0CiteLdd1TlZG7GIQvUzjOs9gZdwxbvEhSYwn6SOaNhc9es0JAfhS0/TeEP0F9ce
# 2vnS1WcaUk8OoVf8iJnBkcyBAz5NcCRks43iCH00fUyAVxJrQ5qZ8sU7H/Lvy0da
# E6ZMswEgJfMQ04uy+wjwiuCdCcBlp/qYgEk1hz1RGeiQIXhFLqGfLOEYwhrMxe6T
# SXBCMo/7xuoc82VokaJNTIIRSFJo3hC9FFdd6BgTZcV/sk+FLEikVoQ11vkunKoA
# FdE3/hoGlMJ8yOobMubKwvSnowMOdKWvObarYBLj6Na59zHh3K3kGKDYwSNHR7Oh
# D26jq22YBoMbt2pnLdK9RBqSEIGPsDsJ18ebMlrC/2pgVItJwZPt4bRc4G/rJvmM
# 1bL5OBDm6s6R9b7T+2+TYTRcvJNFKIM2KmYoX7BzzosmJQayg9Rc9hUZTO1i4F4z
# 8ujo7AqnsAMrkbI2eb73rQgedaZlzLvjSFDzd5Ea/ttQokbIYViY9XwCFjyDKK05
# huzUtw1T0PhH5nUwjewwk3YUpltLXXRhTT8SkXbev1jLchApQfDVxW0mdmgRQRNY
# mtwmKwH0iU1Z23jPgUo+QEdfyYFQc4UQIyFZYIpkVMHMIRroOBl8ZhzNeDhFMJlP
# /2NPTLuqDQhTQXxYPUez+rbsjDIJAsxsPAxWEQIDAQABo4IBWTCCAVUwEgYDVR0T
# AQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUaDfg67Y7+F8Rhvv+YXsIiGX0TkIwHwYD
# VR0jBBgwFoAU7NfjgtJxXWRM3y5nP+e6mK4cD08wDgYDVR0PAQH/BAQDAgGGMBMG
# A1UdJQQMMAoGCCsGAQUFBwMDMHcGCCsGAQUFBwEBBGswaTAkBggrBgEFBQcwAYYY
# aHR0cDovL29jc3AuZGlnaWNlcnQuY29tMEEGCCsGAQUFBzAChjVodHRwOi8vY2Fj
# ZXJ0cy5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVzdGVkUm9vdEc0LmNydDBDBgNV
# HR8EPDA6MDigNqA0hjJodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNlcnRU
# cnVzdGVkUm9vdEc0LmNybDAcBgNVHSAEFTATMAcGBWeBDAEDMAgGBmeBDAEEATAN
# BgkqhkiG9w0BAQwFAAOCAgEAOiNEPY0Idu6PvDqZ01bgAhql+Eg08yy25nRm95Ry
# sQDKr2wwJxMSnpBEn0v9nqN8JtU3vDpdSG2V1T9J9Ce7FoFFUP2cvbaF4HZ+N3HL
# IvdaqpDP9ZNq4+sg0dVQeYiaiorBtr2hSBh+3NiAGhEZGM1hmYFW9snjdufE5Btf
# Q/g+lP92OT2e1JnPSt0o618moZVYSNUa/tcnP/2Q0XaG3RywYFzzDaju4ImhvTnh
# OE7abrs2nfvlIVNaw8rpavGiPttDuDPITzgUkpn13c5UbdldAhQfQDN8A+KVssIh
# dXNSy0bYxDQcoqVLjc1vdjcshT8azibpGL6QB7BDf5WIIIJw8MzK7/0pNVwfiThV
# 9zeKiwmhywvpMRr/LhlcOXHhvpynCgbWJme3kuZOX956rEnPLqR0kq3bPKSchh/j
# wVYbKyP/j7XqiHtwa+aguv06P0WmxOgWkVKLQcBIhEuWTatEQOON8BUozu3xGFYH
# Ki8QxAwIZDwzj64ojDzLj4gLDb879M4ee47vtevLt/B3E+bnKD+sEq6lLyJsQfmC
# XBVmzGwOysWGw/YmMwwHS6DTBwJqakAwSEs0qFEgu60bhQjiWQ1tygVQK+pKHJ6l
# /aCnHwZ05/LWUpD9r4VIIflXO7ScA+2GRfS0YW6/aOImYIbqyK+p/pQd52MbOoZW
# eE4wgge5MIIFoaADAgECAhALDOX/BzyGPKP6JnAWOAwdMA0GCSqGSIb3DQEBCwUA
# MGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwgSW5jLjFBMD8GA1UE
# AxM4RGlnaUNlcnQgVHJ1c3RlZCBHNCBDb2RlIFNpZ25pbmcgUlNBNDA5NiBTSEEz
# ODQgMjAyMSBDQTEwHhcNMjYwODE5MDAwMDAwWhcNMjcwODE4MjM1OTU5WjCBwTET
# MBEGCysGAQQBgjc8AgEDEwJVUzEZMBcGCysGAQQBgjc8AgECEwhEZWxhd2FyZTEd
# MBsGA1UEDwwUUHJpdmF0ZSBPcmdhbml6YXRpb24xEDAOBgNVBAUTBzY2NzU5MTMx
# CzAJBgNVBAYTAlVTMREwDwYDVQQIEwhJbGxpbm9pczEQMA4GA1UEBxMHQ2hpY2Fn
# bzEVMBMGA1UEChMMTmVyZGlvLCBJbmMuMRUwEwYDVQQDEwxOZXJkaW8sIEluYy4w
# ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC0GAXkl6ecx6CDQ9QXP+mP
# oa2GWMIs5Tcw0/BtIZY3EjaJXq9Nmm4RHM+XSnRgae88aXnrIixdz9FIzp1uZ30E
# 4ztt8mfowmP7qhX2dS0BMTn3JN53x6vPsTbgrE419zkAMm2d7QjxSxVk+3dzCCDa
# FBiCe68aVGpRkqbRNMpwC3EoE8/2stzyi/njYbcTCzazXmjBqV7kz0DZfF0xLigt
# 4CWGnY1LxS9dJBESnKKH4dQLyKBpkDA2IM29bEiDhLnSg/wWIX+0lufTX0v3euIh
# tTBGB85lBZXjKt/dqKexGMBmou5WZT9sttYRXLsG9pflvBEhLmOAqA+inS98ii9C
# vd6Ly9D5adcR3InBBBHIx8kQFLOglRiEMCyUYoJ9K0AaHl8xxD0to+J4chG9hLvI
# 1bik+Q7z5Ut2NbdJwV22YLe41wJIQEtZynN2vKhM5GX5nokebXescojq0jeprZU6
# oSFpdcNmIOOBb9iGEpFhD9WvaoT0G6dn9GdCPypxZY3JBL+J8LxGwoxX4eaKx/e/
# 8O5a5FBVz/0yYL17hUmuLBZHtZcsw31cAnovm4DQ9jMBce1VlwrUFKevNzCAW3CR
# RVQx2DEcLTyWP8d6Dczsmy4hQEpUfgiLxyrWduxhNRJ9j/FUVq6AV9+J5gBlB/3H
# QaNVjIyplLqs/6yJRIHh6QIDAQABo4ICAjCCAf4wHwYDVR0jBBgwFoAUaDfg67Y7
# +F8Rhvv+YXsIiGX0TkIwHQYDVR0OBBYEFNQPOC7V6GMYGn9bFaoCiWTci1QwMD0G
# A1UdIAQ2MDQwMgYFZ4EMAQMwKTAnBggrBgEFBQcCARYbaHR0cDovL3d3dy5kaWdp
# Y2VydC5jb20vQ1BTMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcD
# AzCBtQYDVR0fBIGtMIGqMFOgUaBPhk1odHRwOi8vY3JsMy5kaWdpY2VydC5jb20v
# RGlnaUNlcnRUcnVzdGVkRzRDb2RlU2lnbmluZ1JTQTQwOTZTSEEzODQyMDIxQ0Ex
# LmNybDBToFGgT4ZNaHR0cDovL2NybDQuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0VHJ1
# c3RlZEc0Q29kZVNpZ25pbmdSU0E0MDk2U0hBMzg0MjAyMUNBMS5jcmwwgZQGCCsG
# AQUFBwEBBIGHMIGEMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5j
# b20wXAYIKwYBBQUHMAKGUGh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdp
# Q2VydFRydXN0ZWRHNENvZGVTaWduaW5nUlNBNDA5NlNIQTM4NDIwMjFDQTEuY3J0
# MAkGA1UdEwQCMAAwDQYJKoZIhvcNAQELBQADggIBAMrdNPV0udYeYciAelPfj2x0
# VCnkSr1byoRXxsHV2U9jM0xdp0afCHRoaxLIZFvi8M8UzNkvfMelct1gVbIp7ygd
# yYjV0DlOdYVALzmfOuZPzwC02cvtqZkZ3j1sWN/9enqRQiPHv2iZkAdWGWYIvPRW
# q9xT7Qh/+4MsOMdnjleGcb95drHt2s4NagL4/haq1t+Wo+45D6v0r8kUedHLJF4P
# 6MtEbu1vdS1zWysT0SyrK3X3GjaRB6cTLL5S1GtPE92sEc3XU0V4gi8DFKV0Tcko
# ZXaDApg9KTaNii79jr/DLiejN41PODsYNM+zmROUiSHktvAbLV2w0vn0QDB8raCy
# vVBfCkQHqAeuWTQypFRf0NttZ9l9obEGdag2XjibCDZ1qRyjP8dr+XUwRGNZDwIP
# edZN7Bg+F9CA2VHHJHqYzsEOP9GbUAsq6J7i0E5V3ftb4n1327nFKu0HE2BJshz9
# lrRSz2F5fq69O7+imnHedVAUAN4gixuOLBJQMpSJ+YUs9mSlR8wnCCO5wp5kRnKT
# nNXyx6apTwr/ij5YPsH72iApunlJq/ashQd1e8P6ZTcerVXdUHr9Lr3n92sVky+/
# r3Le9IJlhnCQVjAdMsJ9WKa9IkOzC2sgHLe5Ea59kZO0BR/9PXFNyXsB5SAX9pGZ
# Ymvvxj8r7PzbSci8A4e6MYIaqTCCGqUCAQEwfTBpMQswCQYDVQQGEwJVUzEXMBUG
# A1UEChMORGlnaUNlcnQsIEluYy4xQTA/BgNVBAMTOERpZ2lDZXJ0IFRydXN0ZWQg
# RzQgQ29kZSBTaWduaW5nIFJTQTQwOTYgU0hBMzg0IDIwMjEgQ0ExAhALDOX/BzyG
# PKP6JnAWOAwdMA0GCWCGSAFlAwQCAQUAoIGEMBgGCisGAQQBgjcCAQwxCjAIoAKA
# AKECgAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIDgjER3xkbMt/iabIxe8IhoX
# 00AmeHCouhAO5H0FpE66MA0GCSqGSIb3DQEBAQUABIICAHwBYOFbrb7d4gw1DWvW
# Ad+UHRGVOcSsd7h/w7SKmna/FtTTyeiZ3a8/nhO79+0UOhCVCjg+Q9uMMwJKLViy
# o5aZHnCewXiQtyCJml2PeWzeEzqhX+glHp7/4XxO6/Lx78DrJTbbPbf0oxoYOqGw
# EaaH0J0tpax8kQShbYbpNekgQHxfVEiLWOkpBlzYVI3e8nnwzNN7Ls+ctL25S4Wn
# LePW8XF5brEFZRoY/7kbsFjj5U8Nd15EWn1MJqE7Lx9fb4NQTrIuVDk876k/FowC
# 16+0A5NQdjp6jVU98aNaUVEsukSx4ZYKG2kMGJPDZdNV0KfjjmD43tW5qoGf2Uoi
# wui5PB8uR2n6G7Can+vkkmxZoBcj6xmaeIPj1Inxd2C7Z4xzWKvSjHERDGgNo2lh
# wnUCPBO01hGPfAXnto740r+ehjwgMye2Fy/cFNoZJ8t9kk9Aq1J/NVQWwcUiIGgn
# T5mQolgNmQ96HeSonTdTZkfi2Z4RIcQXXMIT61dqy83XOxSDbHaU0KNeBURybA4M
# bwioaaLq++Tm6s+KCUX50MXBtCXleKwQH0/GjFy1qJ/pIv1eCDDaC2x3G249vWBE
# Wmx1eBn6yv+qjt8dhR6kIKUg592p1cDngHLB4omLdph5C1cWu4Q/e7ZiDEyrsC4q
# XaO2ZwbPdExHYDilVeeVkR9joYIXdjCCF3IGCisGAQQBgjcDAwExghdiMIIXXgYJ
# KoZIhvcNAQcCoIIXTzCCF0sCAQMxDzANBglghkgBZQMEAgEFADB3BgsqhkiG9w0B
# CRABBKBoBGYwZAIBAQYJYIZIAYb9bAcBMDEwDQYJYIZIAWUDBAIBBQAEIF1YRmau
# u8I8iakWVa2uqKf4dVomtsFhZG9j09KDu0huAhBGa3ke57nuazjlx8EFlJkTGA8y
# MDI2MDkxMTEyMjI0N1qgghM6MIIG7TCCBNWgAwIBAgIQCE/cM09+RU7bww+P+ZIY
# NTANBgkqhkiG9w0BAQsFADBpMQswCQYDVQQGEwJVUzEXMBUGA1UEChMORGlnaUNl
# cnQsIEluYy4xQTA/BgNVBAMTOERpZ2lDZXJ0IFRydXN0ZWQgRzQgVGltZVN0YW1w
# aW5nIFJTQTQwOTYgU0hBMjU2IDIwMjUgQ0ExMB4XDTI2MDgwNTAwMDAwMFoXDTM3
# MTEwNDIzNTk1OVowYzELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDkRpZ2lDZXJ0LCBJ
# bmMuMTswOQYDVQQDEzJEaWdpQ2VydCBTSEEyNTYgUlNBNDA5NiBUaW1lc3RhbXAg
# UmVzcG9uZGVyIDIwMjYgMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
# ALZ7pvLJ/s1K+NSbTGWz/TjGMPh8CQ6RucZCLv5anHzWJjF/NWJrFIhy24fcpKXl
# gRiky4WAawDfU3YP0BMxt9l3Dm5oCG5Z69AqEN1kgHg2epx+l+lZBcmJCcN0ASUR
# ML5uFIS80sZsDwO3BSkUxDjLJhBI+qiZP3aixAC/qEGLjsBNlLol9VZ7pfGEXiMl
# neJIC5/YKuizVzNFKZZEeoy/0B8Zm+nzKBgSWG52lCO1w+nCg6XpCtklTJXeIg28
# 3hw7TmmsZXR+SMbjbrEOvZ3fP2VxIgeR28Y90ZStd3F9VuA5RVynb/whITPAo9b7
# 5Zr4Ta6Mj3URm26QZYMn/FnbuTegcoRcFEZ9FOqM5T6MTdtr/n74lIT/ug0eeOzm
# Z6QTFg33otX+bFRsIolvykE1jive4PuESaT8zzVeFWDAMDtozNgLctkGD1ZjkEyZ
# tJrLl5ya0m5doH/ScpaZCZVl6pNUOCybMc/kxC6EAmSJY24L0yYKD1Nkddsnb/It
# VKi/2nXpQNMu1PT5prW83vV8d67WowuUs0HdY4H8AMLGvdL/WHEj3ZnqMqAQQP9u
# 3Ai9t+5eQ02GDwy0ODjdzi0xlp70W+ow63/0++YDEX1M0iwgUHwbrJvfpklkZQvw
# 3+kv3vUPItdwroczk9icflf55W1zOEKAcJVAIXpcMCU9AgMBAAGjggGVMIIBkTAM
# BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQUyWOKMC7USvtulPPm40B+9ezN4jAfBgNV
# HSMEGDAWgBTvb1NK6eQGfHrK4pBW9i/USezLTjAOBgNVHQ8BAf8EBAMCB4AwFgYD
# VR0lAQH/BAwwCgYIKwYBBQUHAwgwgZUGCCsGAQUFBwEBBIGIMIGFMCQGCCsGAQUF
# BzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wXQYIKwYBBQUHMAKGUWh0dHA6
# Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRydXN0ZWRHNFRpbWVTdGFt
# cGluZ1JTQTQwOTZTSEEyNTYyMDI1Q0ExLmNydDBfBgNVHR8EWDBWMFSgUqBQhk5o
# dHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVzdGVkRzRUaW1lU3Rh
# bXBpbmdSU0E0MDk2U0hBMjU2MjAyNUNBMS5jcmwwIAYDVR0gBBkwFzAIBgZngQwB
# BAIwCwYJYIZIAYb9bAcBMA0GCSqGSIb3DQEBCwUAA4ICAQCNxTphHp1SCt+ZrAmA
# fn0oQLFr0mLywSLaDXQIENoyKqxrFbJblzCVP/pkXmwXOdrOpWygLzlT12os5ipD
# Cy35RBCg2UMeApEtrfGhz45F4Wt4WGdNdIbRWt3YTYJmpR+b7lr4d7Uwn+H600u4
# D7RnOGf8Wj4UNgAdZkfHhHv1mx9EVh71SJelcEN/oORSjXzdjfw1iZH9d8Nh/thn
# 6hH23d+VsPAr6GAYyzSA02nXD1nYLI7Ijmiv+xLCiYC41DSFYL3GhTiy0PxpawPt
# GRyaBVGzq+UiTfM8pD7KVyF5aQyWP4KhVGUUTnmm/RlYJoW3TiXA/+t0YcT2oRVB
# m3JETjajHug2AL+v5jhtKVnd3D0rbHXEu27o+Q8p4sEWPMqKDB+qbceb6T/6WcwT
# wXmQ9lOCLLYcsQeSWmvKqzpAec9etE14jOQAzLKWdE3w/TCaKtLRaRT7LCkRYVnh
# A2D73FLje1O5b3HR5eHs0NzU/+xX7NbEdcofy0W3Wdwd1XOqtlpg/JgwtKfZM5dq
# O94lbUveOiJBI+xZEbGRsMNbXmMREUTgu+Oca7Y73MPWcslIx2VhkSKSXjDbD6rg
# g39H5Mh7QfieAIjWagkJNt68Yfim6cjEzVSiLSeZfdkr5dtFPTW6jATlWJdYeeDR
# GCyatf8R1hSjzSvdN8yWQPT9gzCCBrQwggScoAMCAQICEA3HrFcF/yGZLkBDIgw6
# SYYwDQYJKoZIhvcNAQELBQAwYjELMAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lD
# ZXJ0IEluYzEZMBcGA1UECxMQd3d3LmRpZ2ljZXJ0LmNvbTEhMB8GA1UEAxMYRGln
# aUNlcnQgVHJ1c3RlZCBSb290IEc0MB4XDTI1MDUwNzAwMDAwMFoXDTM4MDExNDIz
# NTk1OVowaTELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDkRpZ2lDZXJ0LCBJbmMuMUEw
# PwYDVQQDEzhEaWdpQ2VydCBUcnVzdGVkIEc0IFRpbWVTdGFtcGluZyBSU0E0MDk2
# IFNIQTI1NiAyMDI1IENBMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
# ALR4MdMKmEFyvjxGwBysddujRmh0tFEXnU2tjQ2UtZmWgyxU7UNqEY81FzJsQqr5
# G7A6c+Gh/qm8Xi4aPCOo2N8S9SLrC6Kbltqn7SWCWgzbNfiR+2fkHUiljNOqnIVD
# /gG3SYDEAd4dg2dDGpeZGKe+42DFUF0mR/vtLa4+gKPsYfwEu7EEbkC9+0F2w4QJ
# LVSTEG8yAR2CQWIM1iI5PHg62IVwxKSpO0XaF9DPfNBKS7Zazch8NF5vp7eaZ2CV
# NxpqumzTCNSOxm+SAWSuIr21Qomb+zzQWKhxKTVVgtmUPAW35xUUFREmDrMxSNlr
# /NsJyUXzdtFUUt4aS4CEeIY8y9IaaGBpPNXKFifinT7zL2gdFpBP9qh8SdLnEut/
# GcalNeJQ55IuwnKCgs+nrpuQNfVmUB5KlCX3ZA4x5HHKS+rqBvKWxdCyQEEGcbLe
# 1b8Aw4wJkhU1JrPsFfxW1gaou30yZ46t4Y9F20HHfIY4/6vHespYMQmUiote8lad
# jS/nJ0+k6MvqzfpzPDOy5y6gqztiT96Fv/9bH7mQyogxG9QEPHrPV6/7umw052Ak
# yiLA6tQbZl1KhBtTasySkuJDpsZGKdlsjg4u70EwgWbVRSX1Wd4+zoFpp4Ra+MlK
# M2baoD6x0VR4RjSpWM8o5a6D8bpfm4CLKczsG7ZrIGNTAgMBAAGjggFdMIIBWTAS
# BgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBTvb1NK6eQGfHrK4pBW9i/USezL
# TjAfBgNVHSMEGDAWgBTs1+OC0nFdZEzfLmc/57qYrhwPTzAOBgNVHQ8BAf8EBAMC
# AYYwEwYDVR0lBAwwCgYIKwYBBQUHAwgwdwYIKwYBBQUHAQEEazBpMCQGCCsGAQUF
# BzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wQQYIKwYBBQUHMAKGNWh0dHA6
# Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRydXN0ZWRSb290RzQuY3J0
# MEMGA1UdHwQ8MDowOKA2oDSGMmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdp
# Q2VydFRydXN0ZWRSb290RzQuY3JsMCAGA1UdIAQZMBcwCAYGZ4EMAQQCMAsGCWCG
# SAGG/WwHATANBgkqhkiG9w0BAQsFAAOCAgEAF877FoAc/gc9EXZxML2+C8i1NKZ/
# zdCHxYgaMH9Pw5tcBnPw6O6FTGNpoV2V4wzSUGvI9NAzaoQk97frPBtIj+ZLzdp+
# yXdhOP4hCFATuNT+ReOPK0mCefSG+tXqGpYZ3essBS3q8nL2UwM+NMvEuBd/2vmd
# YxDCvwzJv2sRUoKEfJ+nN57mQfQXwcAEGCvRR2qKtntujB71WPYAgwPyWLKu6Rna
# ID/B0ba2H3LUiwDRAXx1Neq9ydOal95CHfmTnM4I+ZI2rVQfjXQA1WSjjf4J2a7j
# LzWGNqNX+DF0SQzHU0pTi4dBwp9nEC8EAqoxW6q17r0z0noDjs6+BFo+z7bKSBwZ
# XTRNivYuve3L2oiKNqetRHdqfMTCW/NmKLJ9M+MtucVGyOxiDf06VXxyKkOirv6o
# 02OoXN4bFzK0vlNMsvhlqgF2puE6FndlENSmE+9JGYxOGLS/D284NHNboDGcmWXf
# wXRy4kbu4QFhOm0xJuF2EZAOk5eCkhSxZON3rGlHqhpB/8MluDezooIs8CVnrpHM
# iD2wL40mm53+/j7tFaxYKIqL0Q4ssd8xHZnIn/7GELH3IdvG2XlM9q7WP/UwgOkw
# /HQtyRN62JK4S1C8uw3PdBunvAZapsiI5YKdvlarEvf8EA+8hcpSM9LHJmyrxaFt
# oza2zNaQ9k+5t1wwggWNMIIEdaADAgECAhAOmxiO+dAt5+/bUOIIQBhaMA0GCSqG
# SIb3DQEBDAUAMGUxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMx
# GTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xJDAiBgNVBAMTG0RpZ2lDZXJ0IEFz
# c3VyZWQgSUQgUm9vdCBDQTAeFw0yMjA4MDEwMDAwMDBaFw0zMTExMDkyMzU5NTla
# MGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsT
# EHd3dy5kaWdpY2VydC5jb20xITAfBgNVBAMTGERpZ2lDZXJ0IFRydXN0ZWQgUm9v
# dCBHNDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAL/mkHNo3rvkXUo8
# MCIwaTPswqclLskhPfKK2FnC4SmnPVirdprNrnsbhA3EMB/zG6Q4FutWxpdtHauy
# efLKEdLkX9YFPFIPUh/GnhWlfr6fqVcWWVVyr2iTcMKyunWZanMylNEQRBAu34Lz
# B4TmdDttceItDBvuINXJIB1jKS3O7F5OyJP4IWGbNOsFxl7sWxq868nPzaw0QF+x
# embud8hIqGZXV59UWI4MK7dPpzDZVu7Ke13jrclPXuU15zHL2pNe3I6PgNq2kZhA
# kHnDeMe2scS1ahg4AxCN2NQ3pC4FfYj1gj4QkXCrVYJBMtfbBHMqbpEBfCFM1Lyu
# GwN1XXhm2ToxRJozQL8I11pJpMLmqaBn3aQnvKFPObURWBf3JFxGj2T3wWmIdph2
# PVldQnaHiZdpekjw4KISG2aadMreSx7nDmOu5tTvkpI6nj3cAORFJYm2mkQZK37A
# lLTSYW3rM9nF30sEAMx9HJXDj/chsrIRt7t/8tWMcCxBYKqxYxhElRp2Yn72gLD7
# 6GSmM9GJB+G9t+ZDpBi4pncB4Q+UDCEdslQpJYls5Q5SUUd0viastkF13nqsX40/
# ybzTQRESW+UQUOsxxcpyFiIJ33xMdT9j7CFfxCBRa2+xq4aLT8LWRV+dIPyhHsXA
# j6KxfgommfXkaS+YHS312amyHeUbAgMBAAGjggE6MIIBNjAPBgNVHRMBAf8EBTAD
# AQH/MB0GA1UdDgQWBBTs1+OC0nFdZEzfLmc/57qYrhwPTzAfBgNVHSMEGDAWgBRF
# 66Kv9JLLgjEtUYunpyGd823IDzAOBgNVHQ8BAf8EBAMCAYYweQYIKwYBBQUHAQEE
# bTBrMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wQwYIKwYB
# BQUHMAKGN2h0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEFzc3Vy
# ZWRJRFJvb3RDQS5jcnQwRQYDVR0fBD4wPDA6oDigNoY0aHR0cDovL2NybDMuZGln
# aWNlcnQuY29tL0RpZ2lDZXJ0QXNzdXJlZElEUm9vdENBLmNybDARBgNVHSAECjAI
# MAYGBFUdIAAwDQYJKoZIhvcNAQEMBQADggEBAHCgv0NcVec4X6CjdBs9thbX979X
# B72arKGHLOyFXqkauyL4hxppVCLtpIh3bb0aFPQTSnovLbc47/T/gLn4offyct4k
# vFIDyE7QKt76LVbP+fT3rDB6mouyXtTP0UNEm0Mh65ZyoUi0mcudT6cGAxN3J0TU
# 53/oWajwvy8LpunyNDzs9wPHh6jSTEAZNUZqaVSwuKFWjuyk1T3osdz9HNj0d1pc
# VIxv76FQPfx2CWiEn2/K2yCNNWAcAgPLILCsWKAOQGPFmCLBsln1VWvPJ6tsds5v
# Iy30fnFqI2si/xK4VC0nftg62fC2h5b9W9FcrBjDTZ9ztwGpn1eqXijiuZQxggN8
# MIIDeAIBATB9MGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwgSW5j
# LjFBMD8GA1UEAxM4RGlnaUNlcnQgVHJ1c3RlZCBHNCBUaW1lU3RhbXBpbmcgUlNB
# NDA5NiBTSEEyNTYgMjAyNSBDQTECEAhP3DNPfkVO28MPj/mSGDUwDQYJYIZIAWUD
# BAIBBQCggdEwGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMBwGCSqGSIb3DQEJ
# BTEPFw0yNjA5MTExMjIyNDdaMCsGCyqGSIb3DQEJEAIMMRwwGjAYMBYEFFHZq9oD
# SXPYT0JmrKSCSOazacQ5MC8GCSqGSIb3DQEJBDEiBCBteN7WWsn4n33Dta3Rz50w
# UsZ+gVEXwQLuAXsw5z+AczA3BgsqhkiG9w0BCRACLzEoMCYwJDAiBCAtoJ2n9BMf
# n+cttsXm6cllZ1WvBD8ep0LMDSEg4UHr/DANBgkqhkiG9w0BAQEFAASCAgCSQ8t3
# xYISIEFuOYf5oZNTsTf8AC9yE6+KtI8GUBeyQ2GC93bjKQUp7TztOsxV3mBZwV/x
# gr+6sKL5uEQh1WWEdg2dPCFZeCW1TLIL47WWbz0FLPABQZAXjwc2OgzobGuIbbAo
# fEokQlLUSR5Q48osanlGuhCXwwl7g757tcaVUQ+3xO3UqNhirQCqMrN7rH4uT7AD
# qVgA6Prh3xhueCHDcsRxbCc5VcDkCsPAREZy87aHXo9YR59fQIRMsZfFK1arIG9L
# oQ5VG+UPFcx9SS918ZNVe6w+VbJB3ynzdUXIoVEWmTjhpsGgL/a+Z8PJXEdhfS4Z
# GGCNDQ4n1VEGVMqVmpl0QUniAWSKfOP4EJhTG4HaKRjUkQrJqXYwRc7DIni2puP8
# UuS1fasJ51M+DDKeUUf4N24aeVWrW30zPgomS+785KldPv4M0gO2nxXxN5jYDpLV
# zHbT0an+5GWuE3HPVrjcaxnT8ak0GwyaFvhw5jdlG2rdGGK0dt+5l/DNEMb6ok6s
# vL8lp6xV7VKTHT0qhfeNPCKa0tDg1ygcwgNav168UFKqyH7AUgFq5lisGHLoUY+j
# znYsMxpirO8tOfq2aKMLC1RkgHnYWVm44ob09KrBUrXvLSZ8c2oCCeBrPQSNU8Vg
# F0n1T/8YXaZFxLKTeLc5RYovBs5zTDAiGVl3vA==
# SIG # End signature block
