
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.9, generator: @autorest/powershell@4.0.758)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for DynamicPoolConfiguration.
.Description
Create an in-memory object for DynamicPoolConfiguration.

#>
function New-NmeDynamicPoolConfigurationModel {
[OutputType([NmePowershell.Models.DynamicPoolConfiguration])]
[CmdletBinding(PositionalBinding=$false)]
param(
    [Parameter(Mandatory)]
    [NmePowershell.PSArgumentCompleterAttribute("Running", "AvailableForConnection")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ActiveHostType},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${AutoHealEnable},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${BurstCapacity},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${HostPoolCapacity},

    [Parameter(Mandatory)]
    [NmePowershell.PSArgumentCompleterAttribute("Count", "Percent")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${HostPoolSizingMeasureType},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${IsEnabled},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${IsSingleUserDesktop},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${MinActiveHostsCount},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${PreStageHostEnable},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${ReImageUsedHosts},

    [Parameter(Mandatory)]
    [NmePowershell.PSArgumentCompleterAttribute("Disabled", "Always", "OnlyWhenScaleInIsAllowed")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ReImageUsedHostsMode},

    [Parameter(Mandatory)]
    [NmePowershell.PSArgumentCompleterAttribute("High", "Medium", "Low")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ScaleInAggressiveness},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${ScaleInRestrictionEnable},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${ScaleInRestrictionPutToDrainMode},

    [Parameter(Mandatory)]
    [NmePowershell.PSArgumentCompleterAttribute("Default", "WorkingHours", "UserDriven")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ScalingMode},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ActiveSessionsScaleCriteriaScaleInHostChangeCount},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Single]
    ${ActiveSessionsScaleCriteriaScaleInValue},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ActiveSessionsScaleCriteriaScaleOutHostChangeCount},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Single]
    ${ActiveSessionsScaleCriteriaScaleOutValue},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String[]]
    ${AdditionalNetworks},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IAutoHealConfigurationItem[]]
    # 
    ${AutoHealConfigs},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("CPUUsage", "RAMUsage", "AvgActiveSessions", "AvailableUserSessionSingle", "AvailableUserSessions", "UserDriven", "PersonalAutoGrow", "PersonalAutoShrink")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${AutoScaleCriteria},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${AutoScaleInterval},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IDynamicPoolTriggerInfo[]]
    # 
    ${AutoScaleTriggers},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("Always", "DuringWorkHours")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${AvailableUserSessionScaleCriterionAvailableSessionRestriction},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${AvailableUserSessionScaleCriterionEndWorkHours},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${AvailableUserSessionScaleCriterionMaxAvailableUserSessions},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${AvailableUserSessionScaleCriterionMinAvailableUserSessions},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${AvailableUserSessionScaleCriterionOutsideWorkHoursSessions},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IAutoHealAction[]]
    # 
    ${ConfigActions},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("0", "1", "2", "3", "4", "5", "6")]
    [NmePowershell.Category('Body')]
    [System.Int32[]]
    ${ConfigDays},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ConfigHostsToBeReady},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("Count", "Percent")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ConfigHostsToBeReadyMeasureType},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ConfigNetworkId},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${ConfigPreStageDiskType},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${ConfigPreStageUnassigned},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${ConfigPreStageUnassignedHosts},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ConfigPrefix},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ConfigResourceGroupId},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("WithoutSessions", "WithoutActive", "WithActive")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ConfigSessionCriteria},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ConfigStaleHeartbeatMinutes},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ConfigSubnet},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ConfigWaitMinutes},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ConfigWaitMinutesBeforeFirstAction},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("Available", "Unavailable", "Shutdown", "Disconnected", "Upgrading", "UpgradeFailed", "NoHeartbeat", "NotJoinedToDomain", "DomainTrustRelationshipLost", "SxSStackListenerNotReady", "FSLogixNotHealthy", "NeedsAssistance")]
    [NmePowershell.Category('Body')]
    [System.String[]]
    ${ConfigWvdStatuses},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("BreadthFirst", "DepthFirst", "Persistent", "MultiplePersistent")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ExtensionLoadBalancing},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ExtensionMaxSessionsPerHost},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${ExtensionStartVMOnConnect},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${HostUsageScaleCriteriaScaleInHostChangeCount},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Single]
    ${HostUsageScaleCriteriaScaleInValue},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${HostUsageScaleCriteriaScaleOutHostChangeCount},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Single]
    ${HostUsageScaleCriteriaScaleOutValue},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("DepthFirst", "BreadthFirst")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${NetworkDistributionStrategy},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IPreStageHostsConfigurationItem[]]
    # 
    ${PreStageHostConfigs},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("Hybrid", "Automated")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${PreStageHostIntelligentPrestageMode},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${PreStageHostIsMultipleConfigsMode},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${RemoveMessagingMessage},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${RemoveMessagingMinutesBeforeRemove},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${RollingDrainModeIsEnabled},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IRollingDrainModeWindow[]]
    # 
    ${RollingDrainModeWindows},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ScaleInAverageTimeRangeInMinutes},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ScaleOutAverageTimeRangeInMinutes},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${SecondaryRegionEnabled},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${StartWorkDuration},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${StartWorkHour},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${StartWorkMinutes},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${StoppedDiskType},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${TimeRangeEndHour},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${TimeRangeEndMinutes},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${TimeRangeStartHour},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${TimeRangeStartMinutes},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${TimezoneId},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${UserDrivenBypassDrainMode},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${UserDrivenMinAvailableSessions},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IUserDrivenPreStageHostsConfigurationItem[]]
    # 
    ${UserDrivenPreStageHostConfigs},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${UserDrivenPreStageHostEnable},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${UserDrivenPreStageHostPreStageIfUnassigned},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${UserDrivenStopDelayMinutes},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("Standard", "Reuse", "Unique")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${VMNamingMode},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${VMTemplateDiskPerformanceTier},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${VMTemplateDiskSize},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("CacheDisk", "ResourceDisk", "NvmeDisk")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${VMTemplateEphemeralOsdiskPlacement},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${VMTemplateHasEphemeralOsdisk},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${VMTemplateImage},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${VMTemplateNetworkId},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${VMTemplatePrefix},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${VMTemplateResourceGroupId},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${VMTemplateSize},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${VMTemplateStorageType},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${VMTemplateSubnet},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("OneTime", "Continuously", "Never")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${WorkingHoursScaleInBehavior},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("OneTime", "Continuously", "Never")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${WorkingHoursScaleOutBehavior}
)

begin {
    try {
        $outBuffer = $null
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer)) {
            $PSBoundParameters['OutBuffer'] = 1
        }
        $parameterSet = $PSCmdlet.ParameterSetName
        
        $testPlayback = $false
        $PSBoundParameters['HttpPipelinePrepend'] | Foreach-Object { if ($_) { $testPlayback = $testPlayback -or ('NmePowershell.Runtime.PipelineMock' -eq $_.Target.GetType().FullName -and 'Playback' -eq $_.Target.Mode) } }

        $mapping = @{
            __AllParameterSets = 'NerdioManagerPowerShell.custom\New-NmeDynamicPoolConfigurationModel';
        }
        $cmdInfo = Get-Command -Name $mapping[$parameterSet]
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessCustomAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessPreviewMessageAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Cmdlet)
        if ($wrappedCmd -eq $null) {
            $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Function)
        }
        $scriptCmd = {& $wrappedCmd @PSBoundParameters}
        $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
        $steppablePipeline.Begin($PSCmdlet)
    } catch {

        throw
    }
}

process {
    try {
        $steppablePipeline.Process($_)
    } catch {

        throw
    }

}
end {
    try {
        $steppablePipeline.End()

    } catch {

        throw
    }
} 
}

# SIG # Begin signature block
# MIIvWAYJKoZIhvcNAQcCoIIvSTCCL0UCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCAw9VH3HC7EUSTU
# KOO0v/H8VnVBqjtAUBRgihLtehardKCCFAUwggWQMIIDeKADAgECAhAFmxtXno4h
# MuI5B72nd3VcMA0GCSqGSIb3DQEBDAUAMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQK
# EwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNV
# BAMTGERpZ2lDZXJ0IFRydXN0ZWQgUm9vdCBHNDAeFw0xMzA4MDExMjAwMDBaFw0z
# ODAxMTUxMjAwMDBaMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJ
# bmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNVBAMTGERpZ2lDZXJ0
# IFRydXN0ZWQgUm9vdCBHNDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
# AL/mkHNo3rvkXUo8MCIwaTPswqclLskhPfKK2FnC4SmnPVirdprNrnsbhA3EMB/z
# G6Q4FutWxpdtHauyefLKEdLkX9YFPFIPUh/GnhWlfr6fqVcWWVVyr2iTcMKyunWZ
# anMylNEQRBAu34LzB4TmdDttceItDBvuINXJIB1jKS3O7F5OyJP4IWGbNOsFxl7s
# Wxq868nPzaw0QF+xembud8hIqGZXV59UWI4MK7dPpzDZVu7Ke13jrclPXuU15zHL
# 2pNe3I6PgNq2kZhAkHnDeMe2scS1ahg4AxCN2NQ3pC4FfYj1gj4QkXCrVYJBMtfb
# BHMqbpEBfCFM1LyuGwN1XXhm2ToxRJozQL8I11pJpMLmqaBn3aQnvKFPObURWBf3
# JFxGj2T3wWmIdph2PVldQnaHiZdpekjw4KISG2aadMreSx7nDmOu5tTvkpI6nj3c
# AORFJYm2mkQZK37AlLTSYW3rM9nF30sEAMx9HJXDj/chsrIRt7t/8tWMcCxBYKqx
# YxhElRp2Yn72gLD76GSmM9GJB+G9t+ZDpBi4pncB4Q+UDCEdslQpJYls5Q5SUUd0
# viastkF13nqsX40/ybzTQRESW+UQUOsxxcpyFiIJ33xMdT9j7CFfxCBRa2+xq4aL
# T8LWRV+dIPyhHsXAj6KxfgommfXkaS+YHS312amyHeUbAgMBAAGjQjBAMA8GA1Ud
# EwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGGMB0GA1UdDgQWBBTs1+OC0nFdZEzf
# Lmc/57qYrhwPTzANBgkqhkiG9w0BAQwFAAOCAgEAu2HZfalsvhfEkRvDoaIAjeNk
# aA9Wz3eucPn9mkqZucl4XAwMX+TmFClWCzZJXURj4K2clhhmGyMNPXnpbWvWVPjS
# PMFDQK4dUPVS/JA7u5iZaWvHwaeoaKQn3J35J64whbn2Z006Po9ZOSJTROvIXQPK
# 7VB6fWIhCoDIc2bRoAVgX+iltKevqPdtNZx8WorWojiZ83iL9E3SIAveBO6Mm0eB
# cg3AFDLvMFkuruBx8lbkapdvklBtlo1oepqyNhR6BvIkuQkRUNcIsbiJeoQjYUIp
# 5aPNoiBB19GcZNnqJqGLFNdMGbJQQXE9P01wI4YMStyB0swylIQNCAmXHE/A7msg
# dDDS4Dk0EIUhFQEI6FUy3nFJ2SgXUE3mvk3RdazQyvtBuEOlqtPDBURPLDab4vri
# RbgjU2wGb2dVf0a1TD9uKFp5JtKkqGKX0h7i7UqLvBv9R0oN32dmfrJbQdA75PQ7
# 9ARj6e/CVABRoIoqyc54zNXqhwQYs86vSYiv85KZtrPmYQ/ShQDnUBrkG5WdGaG5
# nLGbsQAe79APT0JsyQq87kP6OnGlyE0mpTX9iV28hWIdMtKgK1TtmlfB2/oQzxm3
# i0objwG2J5VT6LaJbVu8aNQj6ItRolb58KaAoNYes7wPD1N1KarqE3fk3oyBIa0H
# EEcRrYc9B9F1vM/zZn4wggawMIIEmKADAgECAhAIrUCyYNKcTJ9ezam9k67ZMA0G
# CSqGSIb3DQEBDAUAMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJ
# bmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNVBAMTGERpZ2lDZXJ0
# IFRydXN0ZWQgUm9vdCBHNDAeFw0yMTA0MjkwMDAwMDBaFw0zNjA0MjgyMzU5NTla
# MGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwgSW5jLjFBMD8GA1UE
# AxM4RGlnaUNlcnQgVHJ1c3RlZCBHNCBDb2RlIFNpZ25pbmcgUlNBNDA5NiBTSEEz
# ODQgMjAyMSBDQTEwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDVtC9C
# 0CiteLdd1TlZG7GIQvUzjOs9gZdwxbvEhSYwn6SOaNhc9es0JAfhS0/TeEP0F9ce
# 2vnS1WcaUk8OoVf8iJnBkcyBAz5NcCRks43iCH00fUyAVxJrQ5qZ8sU7H/Lvy0da
# E6ZMswEgJfMQ04uy+wjwiuCdCcBlp/qYgEk1hz1RGeiQIXhFLqGfLOEYwhrMxe6T
# SXBCMo/7xuoc82VokaJNTIIRSFJo3hC9FFdd6BgTZcV/sk+FLEikVoQ11vkunKoA
# FdE3/hoGlMJ8yOobMubKwvSnowMOdKWvObarYBLj6Na59zHh3K3kGKDYwSNHR7Oh
# D26jq22YBoMbt2pnLdK9RBqSEIGPsDsJ18ebMlrC/2pgVItJwZPt4bRc4G/rJvmM
# 1bL5OBDm6s6R9b7T+2+TYTRcvJNFKIM2KmYoX7BzzosmJQayg9Rc9hUZTO1i4F4z
# 8ujo7AqnsAMrkbI2eb73rQgedaZlzLvjSFDzd5Ea/ttQokbIYViY9XwCFjyDKK05
# huzUtw1T0PhH5nUwjewwk3YUpltLXXRhTT8SkXbev1jLchApQfDVxW0mdmgRQRNY
# mtwmKwH0iU1Z23jPgUo+QEdfyYFQc4UQIyFZYIpkVMHMIRroOBl8ZhzNeDhFMJlP
# /2NPTLuqDQhTQXxYPUez+rbsjDIJAsxsPAxWEQIDAQABo4IBWTCCAVUwEgYDVR0T
# AQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUaDfg67Y7+F8Rhvv+YXsIiGX0TkIwHwYD
# VR0jBBgwFoAU7NfjgtJxXWRM3y5nP+e6mK4cD08wDgYDVR0PAQH/BAQDAgGGMBMG
# A1UdJQQMMAoGCCsGAQUFBwMDMHcGCCsGAQUFBwEBBGswaTAkBggrBgEFBQcwAYYY
# aHR0cDovL29jc3AuZGlnaWNlcnQuY29tMEEGCCsGAQUFBzAChjVodHRwOi8vY2Fj
# ZXJ0cy5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVzdGVkUm9vdEc0LmNydDBDBgNV
# HR8EPDA6MDigNqA0hjJodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNlcnRU
# cnVzdGVkUm9vdEc0LmNybDAcBgNVHSAEFTATMAcGBWeBDAEDMAgGBmeBDAEEATAN
# BgkqhkiG9w0BAQwFAAOCAgEAOiNEPY0Idu6PvDqZ01bgAhql+Eg08yy25nRm95Ry
# sQDKr2wwJxMSnpBEn0v9nqN8JtU3vDpdSG2V1T9J9Ce7FoFFUP2cvbaF4HZ+N3HL
# IvdaqpDP9ZNq4+sg0dVQeYiaiorBtr2hSBh+3NiAGhEZGM1hmYFW9snjdufE5Btf
# Q/g+lP92OT2e1JnPSt0o618moZVYSNUa/tcnP/2Q0XaG3RywYFzzDaju4ImhvTnh
# OE7abrs2nfvlIVNaw8rpavGiPttDuDPITzgUkpn13c5UbdldAhQfQDN8A+KVssIh
# dXNSy0bYxDQcoqVLjc1vdjcshT8azibpGL6QB7BDf5WIIIJw8MzK7/0pNVwfiThV
# 9zeKiwmhywvpMRr/LhlcOXHhvpynCgbWJme3kuZOX956rEnPLqR0kq3bPKSchh/j
# wVYbKyP/j7XqiHtwa+aguv06P0WmxOgWkVKLQcBIhEuWTatEQOON8BUozu3xGFYH
# Ki8QxAwIZDwzj64ojDzLj4gLDb879M4ee47vtevLt/B3E+bnKD+sEq6lLyJsQfmC
# XBVmzGwOysWGw/YmMwwHS6DTBwJqakAwSEs0qFEgu60bhQjiWQ1tygVQK+pKHJ6l
# /aCnHwZ05/LWUpD9r4VIIflXO7ScA+2GRfS0YW6/aOImYIbqyK+p/pQd52MbOoZW
# eE4wgge5MIIFoaADAgECAhALDOX/BzyGPKP6JnAWOAwdMA0GCSqGSIb3DQEBCwUA
# MGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwgSW5jLjFBMD8GA1UE
# AxM4RGlnaUNlcnQgVHJ1c3RlZCBHNCBDb2RlIFNpZ25pbmcgUlNBNDA5NiBTSEEz
# ODQgMjAyMSBDQTEwHhcNMjYwODE5MDAwMDAwWhcNMjcwODE4MjM1OTU5WjCBwTET
# MBEGCysGAQQBgjc8AgEDEwJVUzEZMBcGCysGAQQBgjc8AgECEwhEZWxhd2FyZTEd
# MBsGA1UEDwwUUHJpdmF0ZSBPcmdhbml6YXRpb24xEDAOBgNVBAUTBzY2NzU5MTMx
# CzAJBgNVBAYTAlVTMREwDwYDVQQIEwhJbGxpbm9pczEQMA4GA1UEBxMHQ2hpY2Fn
# bzEVMBMGA1UEChMMTmVyZGlvLCBJbmMuMRUwEwYDVQQDEwxOZXJkaW8sIEluYy4w
# ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC0GAXkl6ecx6CDQ9QXP+mP
# oa2GWMIs5Tcw0/BtIZY3EjaJXq9Nmm4RHM+XSnRgae88aXnrIixdz9FIzp1uZ30E
# 4ztt8mfowmP7qhX2dS0BMTn3JN53x6vPsTbgrE419zkAMm2d7QjxSxVk+3dzCCDa
# FBiCe68aVGpRkqbRNMpwC3EoE8/2stzyi/njYbcTCzazXmjBqV7kz0DZfF0xLigt
# 4CWGnY1LxS9dJBESnKKH4dQLyKBpkDA2IM29bEiDhLnSg/wWIX+0lufTX0v3euIh
# tTBGB85lBZXjKt/dqKexGMBmou5WZT9sttYRXLsG9pflvBEhLmOAqA+inS98ii9C
# vd6Ly9D5adcR3InBBBHIx8kQFLOglRiEMCyUYoJ9K0AaHl8xxD0to+J4chG9hLvI
# 1bik+Q7z5Ut2NbdJwV22YLe41wJIQEtZynN2vKhM5GX5nokebXescojq0jeprZU6
# oSFpdcNmIOOBb9iGEpFhD9WvaoT0G6dn9GdCPypxZY3JBL+J8LxGwoxX4eaKx/e/
# 8O5a5FBVz/0yYL17hUmuLBZHtZcsw31cAnovm4DQ9jMBce1VlwrUFKevNzCAW3CR
# RVQx2DEcLTyWP8d6Dczsmy4hQEpUfgiLxyrWduxhNRJ9j/FUVq6AV9+J5gBlB/3H
# QaNVjIyplLqs/6yJRIHh6QIDAQABo4ICAjCCAf4wHwYDVR0jBBgwFoAUaDfg67Y7
# +F8Rhvv+YXsIiGX0TkIwHQYDVR0OBBYEFNQPOC7V6GMYGn9bFaoCiWTci1QwMD0G
# A1UdIAQ2MDQwMgYFZ4EMAQMwKTAnBggrBgEFBQcCARYbaHR0cDovL3d3dy5kaWdp
# Y2VydC5jb20vQ1BTMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcD
# AzCBtQYDVR0fBIGtMIGqMFOgUaBPhk1odHRwOi8vY3JsMy5kaWdpY2VydC5jb20v
# RGlnaUNlcnRUcnVzdGVkRzRDb2RlU2lnbmluZ1JTQTQwOTZTSEEzODQyMDIxQ0Ex
# LmNybDBToFGgT4ZNaHR0cDovL2NybDQuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0VHJ1
# c3RlZEc0Q29kZVNpZ25pbmdSU0E0MDk2U0hBMzg0MjAyMUNBMS5jcmwwgZQGCCsG
# AQUFBwEBBIGHMIGEMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5j
# b20wXAYIKwYBBQUHMAKGUGh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdp
# Q2VydFRydXN0ZWRHNENvZGVTaWduaW5nUlNBNDA5NlNIQTM4NDIwMjFDQTEuY3J0
# MAkGA1UdEwQCMAAwDQYJKoZIhvcNAQELBQADggIBAMrdNPV0udYeYciAelPfj2x0
# VCnkSr1byoRXxsHV2U9jM0xdp0afCHRoaxLIZFvi8M8UzNkvfMelct1gVbIp7ygd
# yYjV0DlOdYVALzmfOuZPzwC02cvtqZkZ3j1sWN/9enqRQiPHv2iZkAdWGWYIvPRW
# q9xT7Qh/+4MsOMdnjleGcb95drHt2s4NagL4/haq1t+Wo+45D6v0r8kUedHLJF4P
# 6MtEbu1vdS1zWysT0SyrK3X3GjaRB6cTLL5S1GtPE92sEc3XU0V4gi8DFKV0Tcko
# ZXaDApg9KTaNii79jr/DLiejN41PODsYNM+zmROUiSHktvAbLV2w0vn0QDB8raCy
# vVBfCkQHqAeuWTQypFRf0NttZ9l9obEGdag2XjibCDZ1qRyjP8dr+XUwRGNZDwIP
# edZN7Bg+F9CA2VHHJHqYzsEOP9GbUAsq6J7i0E5V3ftb4n1327nFKu0HE2BJshz9
# lrRSz2F5fq69O7+imnHedVAUAN4gixuOLBJQMpSJ+YUs9mSlR8wnCCO5wp5kRnKT
# nNXyx6apTwr/ij5YPsH72iApunlJq/ashQd1e8P6ZTcerVXdUHr9Lr3n92sVky+/
# r3Le9IJlhnCQVjAdMsJ9WKa9IkOzC2sgHLe5Ea59kZO0BR/9PXFNyXsB5SAX9pGZ
# Ymvvxj8r7PzbSci8A4e6MYIaqTCCGqUCAQEwfTBpMQswCQYDVQQGEwJVUzEXMBUG
# A1UEChMORGlnaUNlcnQsIEluYy4xQTA/BgNVBAMTOERpZ2lDZXJ0IFRydXN0ZWQg
# RzQgQ29kZSBTaWduaW5nIFJTQTQwOTYgU0hBMzg0IDIwMjEgQ0ExAhALDOX/BzyG
# PKP6JnAWOAwdMA0GCWCGSAFlAwQCAQUAoIGEMBgGCisGAQQBgjcCAQwxCjAIoAKA
# AKECgAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIDYaWnC2DwTstIMewNQCw5Vj
# g4C3bfmXA6DNqouMUjRmMA0GCSqGSIb3DQEBAQUABIICAERkYyuvTORHwZZ/Cbhq
# ywW8stffa9NZFCpCNzNT+FAMRud8JtVt68Ruti3jkbVVgaMJaYaZKsgj/eayXlwu
# 6t+irJKZO6PFeB1TXImHuZFrfBAx42R3waY7KuaqhENLiCG69eOxf0g0qIgkUg1y
# cbjL3mn/x3KX1XamAGMvpA7+M7bdeUWMBcWZELF/OYsrZz/F5ScS3Y7ma/lQF7Jq
# dtfnSe7dNJDJK5ifK6d2fXU9lz7tKnMT9voJFvM03doVF5e4loshCFoxmn1dJmYz
# EDTYkiu0oA94oiwtaCVCRCluzRKZLssFUXoZBDUthn43wmGYLGgZ08KCVpAjUYik
# w3vlvpiLcNGmWh6SmbAxGf/aBYRjzw3YjJD56bC7FHQ/Vl6bsbDJWtDY01AXa3KM
# wsO5HeoZWh6eHdspKnfQhiSE1+37rRCBVZo50bzaJialow7nKUnr00KONlAIQgnC
# +Crf1R/XWz0tvkMYG4sdedRAwUOWyECmrfDgE2Au09cvxjUDfq0+OaEdE5AFokVT
# SGn3MeX3hku7ETqtE76MhDP8X/4oSX33DQgz9/kc2IjbkOnMs/L58IFR4usGqstB
# JoiUXhO3J9JizAyOAQde3zI6BweqtVQaqOoTSUEbWQA25WmcHF+MLaoKT5MQ4ANL
# KodNZ8o3v4gkOWz7M7Tf9ADsoYIXdjCCF3IGCisGAQQBgjcDAwExghdiMIIXXgYJ
# KoZIhvcNAQcCoIIXTzCCF0sCAQMxDzANBglghkgBZQMEAgEFADB3BgsqhkiG9w0B
# CRABBKBoBGYwZAIBAQYJYIZIAYb9bAcBMDEwDQYJYIZIAWUDBAIBBQAEIOIe8QgF
# v0M9laDuXHP6YorbBgzQmQnyIF0oRv4zhH12AhBhDgyYAzWK5kSVVTI5DG/hGA8y
# MDI2MDkxMTEyMjMwM1qgghM6MIIG7TCCBNWgAwIBAgIQCE/cM09+RU7bww+P+ZIY
# NTANBgkqhkiG9w0BAQsFADBpMQswCQYDVQQGEwJVUzEXMBUGA1UEChMORGlnaUNl
# cnQsIEluYy4xQTA/BgNVBAMTOERpZ2lDZXJ0IFRydXN0ZWQgRzQgVGltZVN0YW1w
# aW5nIFJTQTQwOTYgU0hBMjU2IDIwMjUgQ0ExMB4XDTI2MDgwNTAwMDAwMFoXDTM3
# MTEwNDIzNTk1OVowYzELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDkRpZ2lDZXJ0LCBJ
# bmMuMTswOQYDVQQDEzJEaWdpQ2VydCBTSEEyNTYgUlNBNDA5NiBUaW1lc3RhbXAg
# UmVzcG9uZGVyIDIwMjYgMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
# ALZ7pvLJ/s1K+NSbTGWz/TjGMPh8CQ6RucZCLv5anHzWJjF/NWJrFIhy24fcpKXl
# gRiky4WAawDfU3YP0BMxt9l3Dm5oCG5Z69AqEN1kgHg2epx+l+lZBcmJCcN0ASUR
# ML5uFIS80sZsDwO3BSkUxDjLJhBI+qiZP3aixAC/qEGLjsBNlLol9VZ7pfGEXiMl
# neJIC5/YKuizVzNFKZZEeoy/0B8Zm+nzKBgSWG52lCO1w+nCg6XpCtklTJXeIg28
# 3hw7TmmsZXR+SMbjbrEOvZ3fP2VxIgeR28Y90ZStd3F9VuA5RVynb/whITPAo9b7
# 5Zr4Ta6Mj3URm26QZYMn/FnbuTegcoRcFEZ9FOqM5T6MTdtr/n74lIT/ug0eeOzm
# Z6QTFg33otX+bFRsIolvykE1jive4PuESaT8zzVeFWDAMDtozNgLctkGD1ZjkEyZ
# tJrLl5ya0m5doH/ScpaZCZVl6pNUOCybMc/kxC6EAmSJY24L0yYKD1Nkddsnb/It
# VKi/2nXpQNMu1PT5prW83vV8d67WowuUs0HdY4H8AMLGvdL/WHEj3ZnqMqAQQP9u
# 3Ai9t+5eQ02GDwy0ODjdzi0xlp70W+ow63/0++YDEX1M0iwgUHwbrJvfpklkZQvw
# 3+kv3vUPItdwroczk9icflf55W1zOEKAcJVAIXpcMCU9AgMBAAGjggGVMIIBkTAM
# BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQUyWOKMC7USvtulPPm40B+9ezN4jAfBgNV
# HSMEGDAWgBTvb1NK6eQGfHrK4pBW9i/USezLTjAOBgNVHQ8BAf8EBAMCB4AwFgYD
# VR0lAQH/BAwwCgYIKwYBBQUHAwgwgZUGCCsGAQUFBwEBBIGIMIGFMCQGCCsGAQUF
# BzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wXQYIKwYBBQUHMAKGUWh0dHA6
# Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRydXN0ZWRHNFRpbWVTdGFt
# cGluZ1JTQTQwOTZTSEEyNTYyMDI1Q0ExLmNydDBfBgNVHR8EWDBWMFSgUqBQhk5o
# dHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVzdGVkRzRUaW1lU3Rh
# bXBpbmdSU0E0MDk2U0hBMjU2MjAyNUNBMS5jcmwwIAYDVR0gBBkwFzAIBgZngQwB
# BAIwCwYJYIZIAYb9bAcBMA0GCSqGSIb3DQEBCwUAA4ICAQCNxTphHp1SCt+ZrAmA
# fn0oQLFr0mLywSLaDXQIENoyKqxrFbJblzCVP/pkXmwXOdrOpWygLzlT12os5ipD
# Cy35RBCg2UMeApEtrfGhz45F4Wt4WGdNdIbRWt3YTYJmpR+b7lr4d7Uwn+H600u4
# D7RnOGf8Wj4UNgAdZkfHhHv1mx9EVh71SJelcEN/oORSjXzdjfw1iZH9d8Nh/thn
# 6hH23d+VsPAr6GAYyzSA02nXD1nYLI7Ijmiv+xLCiYC41DSFYL3GhTiy0PxpawPt
# GRyaBVGzq+UiTfM8pD7KVyF5aQyWP4KhVGUUTnmm/RlYJoW3TiXA/+t0YcT2oRVB
# m3JETjajHug2AL+v5jhtKVnd3D0rbHXEu27o+Q8p4sEWPMqKDB+qbceb6T/6WcwT
# wXmQ9lOCLLYcsQeSWmvKqzpAec9etE14jOQAzLKWdE3w/TCaKtLRaRT7LCkRYVnh
# A2D73FLje1O5b3HR5eHs0NzU/+xX7NbEdcofy0W3Wdwd1XOqtlpg/JgwtKfZM5dq
# O94lbUveOiJBI+xZEbGRsMNbXmMREUTgu+Oca7Y73MPWcslIx2VhkSKSXjDbD6rg
# g39H5Mh7QfieAIjWagkJNt68Yfim6cjEzVSiLSeZfdkr5dtFPTW6jATlWJdYeeDR
# GCyatf8R1hSjzSvdN8yWQPT9gzCCBrQwggScoAMCAQICEA3HrFcF/yGZLkBDIgw6
# SYYwDQYJKoZIhvcNAQELBQAwYjELMAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lD
# ZXJ0IEluYzEZMBcGA1UECxMQd3d3LmRpZ2ljZXJ0LmNvbTEhMB8GA1UEAxMYRGln
# aUNlcnQgVHJ1c3RlZCBSb290IEc0MB4XDTI1MDUwNzAwMDAwMFoXDTM4MDExNDIz
# NTk1OVowaTELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDkRpZ2lDZXJ0LCBJbmMuMUEw
# PwYDVQQDEzhEaWdpQ2VydCBUcnVzdGVkIEc0IFRpbWVTdGFtcGluZyBSU0E0MDk2
# IFNIQTI1NiAyMDI1IENBMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
# ALR4MdMKmEFyvjxGwBysddujRmh0tFEXnU2tjQ2UtZmWgyxU7UNqEY81FzJsQqr5
# G7A6c+Gh/qm8Xi4aPCOo2N8S9SLrC6Kbltqn7SWCWgzbNfiR+2fkHUiljNOqnIVD
# /gG3SYDEAd4dg2dDGpeZGKe+42DFUF0mR/vtLa4+gKPsYfwEu7EEbkC9+0F2w4QJ
# LVSTEG8yAR2CQWIM1iI5PHg62IVwxKSpO0XaF9DPfNBKS7Zazch8NF5vp7eaZ2CV
# NxpqumzTCNSOxm+SAWSuIr21Qomb+zzQWKhxKTVVgtmUPAW35xUUFREmDrMxSNlr
# /NsJyUXzdtFUUt4aS4CEeIY8y9IaaGBpPNXKFifinT7zL2gdFpBP9qh8SdLnEut/
# GcalNeJQ55IuwnKCgs+nrpuQNfVmUB5KlCX3ZA4x5HHKS+rqBvKWxdCyQEEGcbLe
# 1b8Aw4wJkhU1JrPsFfxW1gaou30yZ46t4Y9F20HHfIY4/6vHespYMQmUiote8lad
# jS/nJ0+k6MvqzfpzPDOy5y6gqztiT96Fv/9bH7mQyogxG9QEPHrPV6/7umw052Ak
# yiLA6tQbZl1KhBtTasySkuJDpsZGKdlsjg4u70EwgWbVRSX1Wd4+zoFpp4Ra+MlK
# M2baoD6x0VR4RjSpWM8o5a6D8bpfm4CLKczsG7ZrIGNTAgMBAAGjggFdMIIBWTAS
# BgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBTvb1NK6eQGfHrK4pBW9i/USezL
# TjAfBgNVHSMEGDAWgBTs1+OC0nFdZEzfLmc/57qYrhwPTzAOBgNVHQ8BAf8EBAMC
# AYYwEwYDVR0lBAwwCgYIKwYBBQUHAwgwdwYIKwYBBQUHAQEEazBpMCQGCCsGAQUF
# BzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wQQYIKwYBBQUHMAKGNWh0dHA6
# Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRydXN0ZWRSb290RzQuY3J0
# MEMGA1UdHwQ8MDowOKA2oDSGMmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdp
# Q2VydFRydXN0ZWRSb290RzQuY3JsMCAGA1UdIAQZMBcwCAYGZ4EMAQQCMAsGCWCG
# SAGG/WwHATANBgkqhkiG9w0BAQsFAAOCAgEAF877FoAc/gc9EXZxML2+C8i1NKZ/
# zdCHxYgaMH9Pw5tcBnPw6O6FTGNpoV2V4wzSUGvI9NAzaoQk97frPBtIj+ZLzdp+
# yXdhOP4hCFATuNT+ReOPK0mCefSG+tXqGpYZ3essBS3q8nL2UwM+NMvEuBd/2vmd
# YxDCvwzJv2sRUoKEfJ+nN57mQfQXwcAEGCvRR2qKtntujB71WPYAgwPyWLKu6Rna
# ID/B0ba2H3LUiwDRAXx1Neq9ydOal95CHfmTnM4I+ZI2rVQfjXQA1WSjjf4J2a7j
# LzWGNqNX+DF0SQzHU0pTi4dBwp9nEC8EAqoxW6q17r0z0noDjs6+BFo+z7bKSBwZ
# XTRNivYuve3L2oiKNqetRHdqfMTCW/NmKLJ9M+MtucVGyOxiDf06VXxyKkOirv6o
# 02OoXN4bFzK0vlNMsvhlqgF2puE6FndlENSmE+9JGYxOGLS/D284NHNboDGcmWXf
# wXRy4kbu4QFhOm0xJuF2EZAOk5eCkhSxZON3rGlHqhpB/8MluDezooIs8CVnrpHM
# iD2wL40mm53+/j7tFaxYKIqL0Q4ssd8xHZnIn/7GELH3IdvG2XlM9q7WP/UwgOkw
# /HQtyRN62JK4S1C8uw3PdBunvAZapsiI5YKdvlarEvf8EA+8hcpSM9LHJmyrxaFt
# oza2zNaQ9k+5t1wwggWNMIIEdaADAgECAhAOmxiO+dAt5+/bUOIIQBhaMA0GCSqG
# SIb3DQEBDAUAMGUxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMx
# GTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xJDAiBgNVBAMTG0RpZ2lDZXJ0IEFz
# c3VyZWQgSUQgUm9vdCBDQTAeFw0yMjA4MDEwMDAwMDBaFw0zMTExMDkyMzU5NTla
# MGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsT
# EHd3dy5kaWdpY2VydC5jb20xITAfBgNVBAMTGERpZ2lDZXJ0IFRydXN0ZWQgUm9v
# dCBHNDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAL/mkHNo3rvkXUo8
# MCIwaTPswqclLskhPfKK2FnC4SmnPVirdprNrnsbhA3EMB/zG6Q4FutWxpdtHauy
# efLKEdLkX9YFPFIPUh/GnhWlfr6fqVcWWVVyr2iTcMKyunWZanMylNEQRBAu34Lz
# B4TmdDttceItDBvuINXJIB1jKS3O7F5OyJP4IWGbNOsFxl7sWxq868nPzaw0QF+x
# embud8hIqGZXV59UWI4MK7dPpzDZVu7Ke13jrclPXuU15zHL2pNe3I6PgNq2kZhA
# kHnDeMe2scS1ahg4AxCN2NQ3pC4FfYj1gj4QkXCrVYJBMtfbBHMqbpEBfCFM1Lyu
# GwN1XXhm2ToxRJozQL8I11pJpMLmqaBn3aQnvKFPObURWBf3JFxGj2T3wWmIdph2
# PVldQnaHiZdpekjw4KISG2aadMreSx7nDmOu5tTvkpI6nj3cAORFJYm2mkQZK37A
# lLTSYW3rM9nF30sEAMx9HJXDj/chsrIRt7t/8tWMcCxBYKqxYxhElRp2Yn72gLD7
# 6GSmM9GJB+G9t+ZDpBi4pncB4Q+UDCEdslQpJYls5Q5SUUd0viastkF13nqsX40/
# ybzTQRESW+UQUOsxxcpyFiIJ33xMdT9j7CFfxCBRa2+xq4aLT8LWRV+dIPyhHsXA
# j6KxfgommfXkaS+YHS312amyHeUbAgMBAAGjggE6MIIBNjAPBgNVHRMBAf8EBTAD
# AQH/MB0GA1UdDgQWBBTs1+OC0nFdZEzfLmc/57qYrhwPTzAfBgNVHSMEGDAWgBRF
# 66Kv9JLLgjEtUYunpyGd823IDzAOBgNVHQ8BAf8EBAMCAYYweQYIKwYBBQUHAQEE
# bTBrMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wQwYIKwYB
# BQUHMAKGN2h0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEFzc3Vy
# ZWRJRFJvb3RDQS5jcnQwRQYDVR0fBD4wPDA6oDigNoY0aHR0cDovL2NybDMuZGln
# aWNlcnQuY29tL0RpZ2lDZXJ0QXNzdXJlZElEUm9vdENBLmNybDARBgNVHSAECjAI
# MAYGBFUdIAAwDQYJKoZIhvcNAQEMBQADggEBAHCgv0NcVec4X6CjdBs9thbX979X
# B72arKGHLOyFXqkauyL4hxppVCLtpIh3bb0aFPQTSnovLbc47/T/gLn4offyct4k
# vFIDyE7QKt76LVbP+fT3rDB6mouyXtTP0UNEm0Mh65ZyoUi0mcudT6cGAxN3J0TU
# 53/oWajwvy8LpunyNDzs9wPHh6jSTEAZNUZqaVSwuKFWjuyk1T3osdz9HNj0d1pc
# VIxv76FQPfx2CWiEn2/K2yCNNWAcAgPLILCsWKAOQGPFmCLBsln1VWvPJ6tsds5v
# Iy30fnFqI2si/xK4VC0nftg62fC2h5b9W9FcrBjDTZ9ztwGpn1eqXijiuZQxggN8
# MIIDeAIBATB9MGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwgSW5j
# LjFBMD8GA1UEAxM4RGlnaUNlcnQgVHJ1c3RlZCBHNCBUaW1lU3RhbXBpbmcgUlNB
# NDA5NiBTSEEyNTYgMjAyNSBDQTECEAhP3DNPfkVO28MPj/mSGDUwDQYJYIZIAWUD
# BAIBBQCggdEwGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMBwGCSqGSIb3DQEJ
# BTEPFw0yNjA5MTExMjIzMDNaMCsGCyqGSIb3DQEJEAIMMRwwGjAYMBYEFFHZq9oD
# SXPYT0JmrKSCSOazacQ5MC8GCSqGSIb3DQEJBDEiBCAMcacMKMqb+QyVfHBcJW2d
# 42xS6sutt/CPLZRu4+g6tDA3BgsqhkiG9w0BCRACLzEoMCYwJDAiBCAtoJ2n9BMf
# n+cttsXm6cllZ1WvBD8ep0LMDSEg4UHr/DANBgkqhkiG9w0BAQEFAASCAgBOR9yQ
# 3DpxESNavwv87Kk5YRtRWhb45HFZUAQwtQ5J0gBwdVyQl2u5gD/IIgh/YiOF0aEe
# KTQjkV+e5Vyuf1xunk4Y4gNVpH4F8GqlGElqfL6quBtTJuTnS0YNSU/8Xg0jKZ/I
# vijvLHlMg4jqzjDuYtgCykepj9Lfp3lz3jBdEvTBGCii0WJkHoNxOydeL5TUuVxG
# oy6R7jyViBZ4ue6CanbT+1hHXNXygNH8ahbxDgsckVa0EGv2x8cAIAz0UYtj31Hm
# 655LX+moLbMDE9nm1dIebZ25DXQ+aqY0lpdkcm1SbR9IvTny8rN/ugkfnsWa+3+U
# 3mee6i0FpP7qG9y0oV83yTg+tm2Yr1aQYQ0aW6O6Lxw9AU1PRjg8GXriSs18mCsb
# 9GBPracVSU0tWR4LoAaHjivwlnPOG/00Xesr1vLLlPA+kf7uGr3cQZ4E/Cu7vZZU
# GOzELyEWdklrEL44BzQ/jf1OxptZ70v7VpadAqStgt71s0qmTNL9tUfIwzVStVd4
# FJ/X3bcBIOLpGX3WZNS6/UaYyhyTfYl3lC+J9Nafyln2xS67X6+6vmaEmr6F7JkR
# mmTF6pNazRCgcFlk220KQ3iO1e89J1vCzU1EHlo5jNYmrC4Q75ut/pIn2bimUzJx
# 8Ono5yKECKOToFQ3ukJZFxcVVsYwcETwuiWbHw==
# SIG # End signature block
