
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for HostPoolScriptedActionsAssignment.
.Description
Create an in-memory object for HostPoolScriptedActionsAssignment.

#>
function New-NmeHostPoolScriptedActionsAssignmentModel {
[OutputType([NmePowershell.Models.HostPoolScriptedActionsAssignment])]
[CmdletBinding(PositionalBinding=$false)]
param(
    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${OnCreateActiveDirectoryId},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${OnCreateEnabled},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IScriptedActionOption[]]
    # 
    ${OnCreateScriptedActions},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${OnHostCreateActiveDirectoryId},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${OnHostCreateEnabled},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IScriptedActionOption[]]
    # 
    ${OnHostCreateScriptedActions},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${OnRemoveActiveDirectoryId},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${OnRemoveEnabled},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IScriptedActionOption[]]
    # 
    ${OnRemoveScriptedActions},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${OnStartActiveDirectoryId},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${OnStartEnabled},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IScriptedActionOption[]]
    # 
    ${OnStartScriptedActions},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${OnStopActiveDirectoryId},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${OnStopEnabled},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IScriptedActionOption[]]
    # 
    ${OnStopScriptedActions},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # Shared scripted actions profile ID.
    ${ProfileId}
)

begin {
    try {
        $outBuffer = $null
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer)) {
            $PSBoundParameters['OutBuffer'] = 1
        }
        $parameterSet = $PSCmdlet.ParameterSetName
        
        $testPlayback = $false
        $PSBoundParameters['HttpPipelinePrepend'] | Foreach-Object { if ($_) { $testPlayback = $testPlayback -or ('NmePowershell.Runtime.PipelineMock' -eq $_.Target.GetType().FullName -and 'Playback' -eq $_.Target.Mode) } }

        $mapping = @{
            __AllParameterSets = 'NerdioManagerPowerShell.custom\New-NmeHostPoolScriptedActionsAssignmentModel';
        }
        $cmdInfo = Get-Command -Name $mapping[$parameterSet]
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessCustomAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessPreviewMessageAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Cmdlet)
        if ($wrappedCmd -eq $null) {
            $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Function)
        }
        $scriptCmd = {& $wrappedCmd @PSBoundParameters}
        $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
        $steppablePipeline.Begin($PSCmdlet)
    } catch {

        throw
    }
}

process {
    try {
        $steppablePipeline.Process($_)
    } catch {

        throw
    }

}
end {
    try {
        $steppablePipeline.End()

    } catch {

        throw
    }
} 
}
