
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Patch scripted actions assignment for ARM host pool
.Description
Patch scripted actions assignment for ARM host pool

#>
function Update-NmeHostPoolScriptedAction {
[OutputType([NmePowershell.Models.IHostPoolScriptedActionsAssignment])]
[CmdletBinding(DefaultParameterSetName='UpdateExpanded', PositionalBinding=$false, SupportsShouldProcess, ConfirmImpact='Medium')]
param(
    [Parameter(Mandatory)]
    [NmePowershell.Category('Path')]
    [System.String]
    # .
    ${HostPoolName},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Path')]
    [System.String]
    # .
    ${ResourceGroup},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Path')]
    [System.String]
    # .
    ${SubscriptionId},

    [Parameter(ParameterSetName='Update', Mandatory, ValueFromPipeline)]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IHostPoolScriptedActionsAssignment]
    # .
    ${Body},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${OnCreateActiveDirectoryId},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${OnCreateEnabled},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [AllowEmptyCollection()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IScriptedActionOption[]]
    # .
    ${OnCreateScriptedActions},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${OnHostCreateActiveDirectoryId},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${OnHostCreateEnabled},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [AllowEmptyCollection()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IScriptedActionOption[]]
    # .
    ${OnHostCreateScriptedActions},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${OnRemoveActiveDirectoryId},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${OnRemoveEnabled},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [AllowEmptyCollection()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IScriptedActionOption[]]
    # .
    ${OnRemoveScriptedActions},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${OnStartActiveDirectoryId},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${OnStartEnabled},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [AllowEmptyCollection()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IScriptedActionOption[]]
    # .
    ${OnStartScriptedActions},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${OnStopActiveDirectoryId},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${OnStopEnabled},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [AllowEmptyCollection()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IScriptedActionOption[]]
    # .
    ${OnStopScriptedActions},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # Shared scripted actions profile ID.
    ${ProfileId},

    [Parameter(DontShow)]
    [NmePowershell.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Wait for .NET debugger to attach
    ${Break},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [NmePowershell.Category('Runtime')]
    [NmePowershell.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be appended to the front of the pipeline
    ${HttpPipelineAppend},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [NmePowershell.Category('Runtime')]
    [NmePowershell.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be prepended to the front of the pipeline
    ${HttpPipelinePrepend},

    [Parameter(DontShow)]
    [NmePowershell.Category('Runtime')]
    [System.Uri]
    # The URI for the proxy server to use
    ${Proxy},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [NmePowershell.Category('Runtime')]
    [System.Management.Automation.PSCredential]
    # Credentials for a proxy server to use for the remote call
    ${ProxyCredential},

    [Parameter(DontShow)]
    [NmePowershell.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Use the default credentials for the proxy
    ${ProxyUseDefaultCredentials}
)

begin {
    try {
        $outBuffer = $null
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer)) {
            $PSBoundParameters['OutBuffer'] = 1
        }
        $parameterSet = $PSCmdlet.ParameterSetName
        
        $testPlayback = $false
        $PSBoundParameters['HttpPipelinePrepend'] | Foreach-Object { if ($_) { $testPlayback = $testPlayback -or ('NmePowershell.Runtime.PipelineMock' -eq $_.Target.GetType().FullName -and 'Playback' -eq $_.Target.Mode) } }

        $mapping = @{
            Update = 'NerdioManagerPowerShell.private\Update-NmeHostPoolScriptedAction_Update';
            UpdateExpanded = 'NerdioManagerPowerShell.private\Update-NmeHostPoolScriptedAction_UpdateExpanded';
        }
        $cmdInfo = Get-Command -Name $mapping[$parameterSet]
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessCustomAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessPreviewMessageAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Cmdlet)
        if ($wrappedCmd -eq $null) {
            $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Function)
        }
        $scriptCmd = {& $wrappedCmd @PSBoundParameters}
        $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
        $steppablePipeline.Begin($PSCmdlet)
    } catch {

        throw
    }
}

process {
    try {
        $steppablePipeline.Process($_)
    } catch {

        throw
    }

}
end {
    try {
        $steppablePipeline.End()

    } catch {

        throw
    }
} 
}
